### ISSUE TITLE
LibAcoustics apparently crushes when writing outputs

### ISSUE THREAD

**Issue by HBRu** [unicfdlab/libAcoustics#10]
Dear libAcoustics developers,

Using your library, I can only simulate less than one second due to an error that I present in what follows:

`[0] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[0] #1  Foam::sigFpe::sigHandler(int) at ??:?
[0] #2  ? in "/lib/x86_64-linux-gnu/libc.so.6"
[0] #3  Foam::SoundObserver::fft(double) const at ??:?
[0] #4  Foam::functionObjects::AcousticAnalogy::writeFft() at ??:?
[0] #5  Foam::functionObjects::AcousticAnalogy::write() at ??:?
[0] #6  Foam::functionObjectList::execute() at ??:?
[0] #7  Foam::Time::run() const at ??:?
[0] #8  Foam::Time::loop() at ??:?
[0] #9  ? at ??:?
[0] #10  __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
[0] #11  ? at ??:?
[cauchy:27218] *** Process received signal ***
[cauchy:27218] Signal: Floating point exception (8)
[cauchy:27218] Signal code:  (-6)
[cauchy:27218] Failing at address: 0x64c804a700006a52
[cauchy:27218] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x7ff4cdf83cb0]
[cauchy:27218] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7ff4cdf83c37]
[cauchy:27218] [ 2] /lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x7ff4cdf83cb0]
[cauchy:27218] [ 3] /opt/OpenFOAM-4.1/platforms/linux64GccDPInt32Opt/lib/libAcoustics.so(_ZNK4Foam13SoundObserver3fftEd+0x1bd) [0x7ff4c4fcaa7d]
[cauchy:27218] [ 4] /opt/OpenFOAM-4.1/platforms/linux64GccDPInt32Opt/lib/libAcoustics.so(_ZN4Foam15functionObjects15AcousticAnalogy8writeFftEv+0x207) [0x7ff4c4fcc987]
[cauchy:27218] [ 5] /opt/OpenFOAM-4.1/platforms/linux64GccDPInt32Opt/lib/libAcoustics.so(_ZN4Foam15functionObjects15AcousticAnalogy5writeEv+0x18d) [0x7ff4c4fcfc9d]
[cauchy:27218] [ 6] /opt/OpenFOAM-4.1/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so(_ZN4Foam18functionObjectList7executeEv+0x63) [0x7ff4cf0daf83]
[cauchy:27218] [ 7] /opt/OpenFOAM-4.1/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so(_ZNK4Foam4Time3runEv+0x8f) [0x7ff4cf0e888f]
[cauchy:27218] [ 8] /opt/OpenFOAM-4.1/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so(_ZN4Foam4Time4loopEv+0x12) [0x7ff4cf0e87e2]
[cauchy:27218] [ 9] pisoFoam() [0x422790]
[cauchy:27218] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7ff4cdf6ef45]
[cauchy:27218] [11] pisoFoam() [0x423ed6]
[cauchy:27218] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 27218 on node cauchy exited on signal 8 (Floating point exception).
`

This error appears exactly after the print:
Starting acoustics probe

To give the acoustic pressure in the collocated sensors.

I am running pisoFoam, incompressible and SA-LES turbulence model for a 0012 NACA airfoil with. The complete case runs without any error If the library is not used.

I am not sure about the reason this error appears neither how can I proceed to fix it. Please I  ask you for help and possibly any guidance to fix it.
Any kind of help would be really appreciated.

Thank you in advance,
Héctor

**Comment by AndreyEpikhin** [comment]
Hi Héctor,
This error may occur due to out of memory on the computer core. You can try to reduce the number of cells on the STL surfaces or the count of observer points and restart calculation.
