### ISSUE TITLE
Difference between patches and surfaces in control files

### ISSUE THREAD

**Issue by MarcusAW** [unicfdlab/libAcoustics#107]
Hi,
This should be a simple question, but what is the difference between patches and surface in fwhControl?
In the vortexShed tutorial if I would like to only consider the noise generation of just the cylinder patch, it seems like there is no need to define patches when surface is defined. 

Any clarification would be appreciated,
Marcus

**Comment by mkraposhin** [comment]
When you use impermeable patches, the analogy reduces to Curle.  Indeed, when you solve only for noise generated by flow over a non-moving object, you don't need any additional surfaces except the patch encompassing the body.

**Comment by kdg5424** [comment]
Hello @mkraposhin.
I tried a fan case with patches and without patches.
Blades rotate around 2,000rpm.
And the result is same.

In this case, don't I need also any patches?

Actually, I still don't understand the differences between patches and surfaces.

**Comment by mkraposhin** [comment]
If you want to measure a sound response from a moving source with solid walls  and you can simulate the source motion with OpenFOAM, then you don't need STL surfaces and you can use patches. However, if you want to measure the response from some source that doesn't have walls (for example, jet), or for example, you are modelling blades motion via volume forces, you can't use patches and you thus you have to use STL surfaces.
