### ISSUE TITLE
Options for predicting acoustic field of rotating blade using MRF

### ISSUE THREAD

**Issue by niall-oneill** [unicfdlab/libAcoustics#114]
Hello, 
I am running on limited computational resources so I am using MRF to simulate a single blade of a wind turbine with periodic BC's. What steps could I take to generate acoustic field predictions? I have not been able to find any examples or discussions on this topic online. 

The closest thing I have see was an implementation predicting noise of an axisymmetric turbomachine that used SRF. This included some minor changes to "1 void Foam::functionObjects::fwhFormulation::initialize()" files by the looks of it and can be found at [https://www.tfd.chalmers.se/~hani/kurser/OS_CFD_2021/DebarsheeGhosh/OSCFD21_FinalPresentation.pdf]
The only thing with this, is that he used SRFPimpleFOAM, which is still a transient solver and I am assuming that I do not have the resources to run this. 

I will do what I can to try and access resources to allow me to run URANS simulations, but I would really appreciate if someone knew of a way to incoroprate MRF in the meantime. Thanks :)

 @unicfdlab

**Comment by mkraposhin** [comment]
Hello, sir! The question you are asking is not about OpenFOAM - it is about CAA theory and about the scopes of application  of acoustics analogies. Usually acoustics analogies are 3D and transient by their nature. Therefore, I hardly can imagine a steady state solver with some type of symmetry that can be helpful for you. 

Certainly, under some conditions you can imagine your one blade as a single source of sound that can be multiplied (for example like non-coherent sources) to estimate total contribution to your acoustic field. But  this is more theoretical work than technical. But I don't think you can predict a sound field using MRF steady state simulation of aerodynamics.

**Comment by niall-oneill** [comment]
> Hello, sir! The question you are asking is not about OpenFOAM - it is about CAA theory and about the scopes of application of acoustics analogies. Usually acoustics analogies are 3D and transient by their nature. Therefore, I hardly can imagine a steady state solver with some type of symmetry that can be helpful for you.
> 
> Certainly, under some conditions you can imagine your one blade as a single source of sound that can be multiplied (for example like non-coherent sources) to estimate total contribution to your acoustic field. But this is more theoretical work than technical. But I don't think you can predict a sound field using MRF steady state simulation of aerodynamics.

I see, I'm sure you can tell I am new to CAA, thanks very much at least I know my options now!
