### ISSUE TITLE
Error in reading the binary mesh.

### ISSUE THREAD

**Issue by wanglican** [unicfdlab/libAcoustics#13]
Hello everyone,
    Recently, the libAcoustics is installed in OpenFOAM 4.1 and the 1D/2D tutorials with blockMeshDict can run successfully with the operator ./Allrun. However, the 3D tutorials such as libAcoustics/Tutorials-4.1/monopole3D are broken due to the binary type of mesh. In general, we usually use the ASCII type. So, is there an operation to convert a binary mesh into an ASCII mesh?
    Thank you in advance.
```
Create mesh
--> FOAM FATAL IO ERROR: 
Expected a ')' while reading binaryBlock, found on line 20 the word 'R'
file: /home/OpenFOAM/libAcoustics/Tutorials-4.1/monopole3D/constant/polyMesh/faces at line 20.
    From function Foam::Istream& Foam::Istream::readEnd(const char*)
    in file db/IOstreams/IOstreams/Istream.C at line 109.
FOAM exiting
```

**Comment by unicfdlab** [comment]
It looks like this is an OpenFOAM error. Try to switch to OpenFOAM+1812
