### ISSUE TITLE
Can't compile on OpenFOAM-1812

### ISSUE THREAD

**Issue by mojtabaAmiraslanpour** [unicfdlab/libAcoustics#14]
Hi. I tried compiling libAcoustics on OpenFOAM-1812 but I got this error:
```
In file included from surfaceNoise.C:100:0:
createFields.H: In function 'int main(int, char**)':
createFields.H:26:57: error: conversion from 'Foam::ITstream' to non-scalar type 'Foam::fileName' requested
     fileName inputFileName = dict.lookup("inputFileName");
                                                         ^
make: *** [Make/linux64GccDPInt32Opt/surfaceNoise.o] Error 1
```

**Comment by unicfdlab** [comment]
Hi, new one version for OpenFOAM+-1812 is available: checkout branch digitef-dev-1812, please

**Comment by zeineldin117** [comment]
is it possible to use branch digitef-dev-1812 for openFoam v1902

**Comment by unicfdlab** [comment]
It is possible to use  branch digitef-dev-1912 for openFoam v1912. However, we didn't test everything up to now.

**Comment by zeineldin117** [comment]
I have tried to install libAcoustics-digitef-dev-1912 to version 1906 but i get an error message 

__________________________________________________________________________________________________________
g++ -std=c++11 -m64 -DOPENFOAM=1906 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas -O3  -DNoRepository -ftemplate-depth-100 -I/data/openFOAM/OpenFOAM-v1906/src/randomProcesses/lnInclude -I/data/openFOAM/OpenFOAM-v1906/src/sampling/lnInclude -I../../lib/lnInclude -I/data/openFOAM/ThirdParty-v1906/platforms/linux64Gcc/fftw-3.3.7/include -IlnInclude -I. -I/data/openFOAM/OpenFOAM-v1906/src/OpenFOAM/lnInclude -I/data/openFOAM/OpenFOAM-v1906/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/FileInterface/FileInterface.o Make/linux64GccDPInt32Opt/Interpolator/Interpolator.o Make/linux64GccDPInt32Opt/surfaceNoise.o -L/data/openFOAM/OpenFOAM-v1906/platforms/linux64GccDPInt32Opt/lib \
    -lrandomProcesses -lsampling -L/home/zels496/OpenFOAM/zels496-v1906/platforms/linux64GccDPInt32Opt/lib -lAcoustics -L/data/openFOAM/ThirdParty-v1906/platforms/linux64Gcc/fftw-3.3.7/lib64 -lfftw3 -lOpenFOAM -ldl  \
     -lm -o /home/zels496/OpenFOAM/zels496-v1906/platforms/linux64GccDPInt32Opt/bin/surfaceNoise
Make/linux64GccDPInt32Opt/FileInterface/FileInterface.o: In function `Foam::FileInterface::read()':
FileInterface.C:(.text+0x18cd): undefined reference to `Foam::string::removeEnd(char)'
Make/linux64GccDPInt32Opt/surfaceNoise.o: In function `Foam::fileName::fileName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, bool) [clone .constprop.83]':
surfaceNoise.C:(.text+0x2c7): undefined reference to `Foam::string::removeEnd(char)'
Make/linux64GccDPInt32Opt/surfaceNoise.o: In function `Foam::fileName::lessExt() const':
surfaceNoise.C:(.text._ZNK4Foam8fileName7lessExtEv[_ZNK4Foam8fileName7lessExtEv]+0x33b): undefined reference to `Foam::string::removeEnd(char)'
Make/linux64GccDPInt32Opt/surfaceNoise.o: In function `void Foam::dictionary::reportDefault<double>(Foam::word const&, double const&, bool) const':
surfaceNoise.C:(.text._ZNK4Foam10dictionary13reportDefaultIdEEvRKNS_4wordERKT_b[_ZNK4Foam10dictionary13reportDefaultIdEEvRKNS_4wordERKT_b]+0x28): undefined reference to `Foam::dictionary::relativeName(bool) const'
surfaceNoise.C:(.text._ZNK4Foam10dictionary13reportDefaultIdEEvRKNS_4wordERKT_b[_ZNK4Foam10dictionary13reportDefaultIdEEvRKNS_4wordERKT_b]+0x2f): undefined reference to `Foam::InfoErr'
Make/linux64GccDPInt32Opt/surfaceNoise.o: In function `void Foam::dictionary::reportDefault<Foam::word>(Foam::word const&, Foam::word const&, bool) const':
surfaceNoise.C:(.text._ZNK4Foam10dictionary13reportDefaultINS_4wordEEEvRKS2_RKT_b[_ZNK4Foam10dictionary13reportDefaultINS_4wordEEEvRKS2_RKT_b]+0x26): undefined reference to `Foam::dictionary::relativeName(bool) const'
surfaceNoise.C:(.text._ZNK4Foam10dictionary13reportDefaultINS_4wordEEEvRKS2_RKT_b[_ZNK4Foam10dictionary13reportDefaultINS_4wordEEEvRKS2_RKT_b]+0x2d): undefined reference to `Foam::InfoErr'
Make/linux64GccDPInt32Opt/surfaceNoise.o: In function `main':
surfaceNoise.C:(.text.startup+0x1b59): undefined reference to `Foam::string::removeEnd(char)'
surfaceNoise.C:(.text.startup+0x1ef1): undefined reference to `Foam::string::removeEnd(char)'
collect2: error: ld returned 1 exit status
/data/openFOAM/OpenFOAM-v1906/wmake/makefiles/general:140: recipe for target '/home/zels496/OpenFOAM/zels496-v1906/platforms/linux64GccDPInt32Opt/bin/surfaceNoise' failed
make: *** [/home/zels496/OpenFOAM/zels496-v1906/platforms/linux64GccDPInt32Opt/bin/surfaceNoise] Error 1
__________________________________________________________________________________________________________

can you help me in solving that problem?

**Comment by unicfdlab** [comment]
Hey, we haven't tested libAcoustics with OpenFOAM+ v1906 and we do not plans to support any of XX06 versions of OpenFOAM+. Can you try with OpenFOAM+ 1912?
