### ISSUE TITLE
compiling error for v4.1

### ISSUE THREAD

**Issue by zach-uky** [unicfdlab/libAcoustics#15]
Dear Author,

When I compile the v4.1 under openfoam1812, some errors pop up as 
FoamFourierAnalysis/FoamFftwDriver.C:19:9: error: call of overloaded ‘autoPtr(int)’ is ambiguous

createFields.H:26:41: error: conversion from ‘Foam::ITstream’ to non-scalar type ‘Foam::fileName’ requested
     fileName inputFileName = dict.lookup("inputFileName");

My gcc is version 7.4.

**Comment by unicfdlab** [comment]
Hi, 
please use branch digitef-dev-1812  for OpenFOAM v1812
