### ISSUE TITLE
no make directory for   /home/liuliyun/libAcoustics-digitef-dev-1812/Sources/app/surfaceNoise

### ISSUE THREAD

**Issue by llyscj** [unicfdlab/libAcoustics#18]
hi , I tried compiling libAcoustics-digitef-dev-1812 on the OpenFOAMv1812, i got this error:

no make directory directory for   for /home/liuliyun/libAcoustics-digitef-dev-1812/Sources/app/surfaceNoise

so , I check this directory , make file is not there. 

can you send me the make file please, thanks  a lot.

email:  liuliyun@sjtu.edu.cn

**Comment by vkorchagova** [comment]
Dear llyscj,
the folder  /home/liuliyun/libAcoustics-digitef-dev-1812/Sources/app/surfaceNoise/Make  has been uploaded to git.
