### ISSUE TITLE
can't compile  OpenFOAM-1812

### ISSUE THREAD

**Issue by phantazord** [unicfdlab/libAcoustics#20]
I'm trying to compile libAcoustic but I'm getting this error:

In file included from surfaceNoise.C:100:0:
createFields.H: In function ‘int main(int, char**)’:
createFields.H:8:5: error: ‘IOdictionary’ was not declared in this scope
     IOdictionary dict
     ^~~~~~~~~~~~
*** [Make/linux64GccDPInt32Opt/surfaceNoise.o] Error 1

**Comment by engenegr** [comment]
Hey.
As soon as in Foundation release, there must be `#include "IOdictionary.H" ` in the surfaceNoise.C.

**Comment by VatutinKirill** [comment]
Hello. Can you show us you system environment? I think there are some problems.

**Comment by phantazord** [comment]
Hi. Thank you for the reply. I'm using the branch digitef-dev-1812, but now appears this new error:


In file included from surfaceNoise.C:101:0:
createFields.H: In function ‘int main(int, char**)’:
createFields.H:26:35: error: ‘class Foam::IOdictionary’ has no member named ‘get’; did you mean ‘set’?
     fileName inputFileName = dict.get<word>("inputFileName");
                                                     ^~~
                                                     set
createFields.H:26:43: error: expected primary-expression before ‘>’ token
     fileName inputFileName = dict.get<word>("inputFileName");
                                           ^
*** [Make/linux64GccDPInt32Opt/surfaceNoise.o] Error 1

**Comment by VatutinKirill** [comment]
Type command "export" in terminal and copy output here, let's check OpenFOAM environment.

**Comment by VatutinKirill** [comment]
You are using wrong version of OpenFOAM, you can download right version here: https://www.openfoam.com/releases/openfoam-v1812
If you already install it you should source correct bashrc(OpenFOAM-v1812 environment instead OpenFOAM-6 environment)
