### ISSUE TITLE
the p_fluct got based on the libacoustics is not equal to the p flucutation I get by the utility probe.

### ISSUE THREAD

**Issue by llyscj** [unicfdlab/libAcoustics#21]
I am running a 3d square cylinder case , it runs well, but the acoustic pressure I got based on the libacoustics is inconsistent with the flow field pressure fluctuation, they differ from each other a lot.More specifically, 
![1](https://user-images.githubusercontent.com/40813352/68000653-edb98680-fc9b-11e9-9cc8-c839e0198810.jpg)

I extract the p using the utility probe,  get the real p_fluctuation by  p*rho-pmean-p0, this value is not equal to the pFluct  which is got based on the Libacoustics. I am really confused .

besides,   the size of the square is 2e-4   Multiply  2e-4 Multiply  1e-6, for its 3d case ,is it right to set the dRef=1?

and, when begin running the case, I always get such kind of warnings as flows. It seems that the warnings are associated with libacoustics, how to solve this? Thanks a lot. I am really appreciated！
![1](https://user-images.githubusercontent.com/40813352/68001046-5fde9b00-fc9d-11e9-8bb8-0412a11b4b69.png)
![2](https://user-images.githubusercontent.com/40813352/68001048-60773180-fc9d-11e9-931a-215df347eca9.png)

**Comment by VatutinKirill** [comment]
This error means that you  already have libs with same name somewhere. It is not easy to find error in your solution without information about solver, mesh and parameters  of case. dRef=1 seems to be Ok.
