### ISSUE TITLE
cannot find -lAcoustics and -lfftw3

### ISSUE THREAD

**Issue by Chansfoam** [unicfdlab/libAcoustics#22]
Dear author:
I am using OpenFoam 6 version. I have trouble in making file. It says cannot find -lAcoustics and -lfftw3. Why is that?
Thanks for watching. I am looking forward to hearing from you.  

https://app.leanboard.io/board/dd839fac-45bc-4e58-b727-ba8e922da865

**Comment by VatutinKirill** [comment]
As you can see, github project for libAcoustics don't have branch for OpenFOAM-6. The latest version is for  OpenFOAM-v1812 in branch  digitef-dev-1812
You are using wrong version of OpenFOAM, you can download right version here: https://www.openfoam.com/releases/openfoam-v1812.
or you can download:
https://github.com/unicfdlab/OpenDTEF  from branch v1812
or can ask for DigiTEF or try compile it by yourself:
https://github.com/unicfdlab/DigiTEF

**Comment by Chansfoam** [comment]
Dear author:
Thanks for your help! Now I have already downloaded and compiled the OpenFOAM-v1812, yet it's still missing -lAcoustics and -lfftw3 and in addition, -lrandomProcesses file. 
I am sure it's making at the beginning. Then it reported from FoamFftwDriver.C that fftw3.h is unavailable. 
I just run the wmakeAll.sh in Source file:
`./wmakeAll.sh`
Did I miss something?
Thanks again, I am really appreciate if I could use and learn your code for my research.

**Comment by VatutinKirill** [comment]
Type command "export" in terminal and copy output here, let's check OpenFOAM environment.
There can be some problems with path to  $(FFTW_ARCH_PATH).

**Comment by Chansfoam** [comment]
I copy the output of  $(FFTW_ARCH_PATH):

> declare -x FFTW_ARCH_PATH="/home/nanbert/OpenFOAM/OpenFOAM-v1812/ThirdParty/platforms/linux64Gcc/fftw-3.3.7"

**I may found the problem.** The corresponding **ThirdParty** file was not installed with OpenFOAM-v1812. I noticed the ThirdParty in the path above, but I cannot find it in the real path of my computer.

**Comment by unicfdlab** [comment]
> I copy the output of $(FFTW_ARCH_PATH):
> 
> > declare -x FFTW_ARCH_PATH="/home/nanbert/OpenFOAM/OpenFOAM-v1812/ThirdParty/platforms/linux64Gcc/fftw-3.3.7"
> 
> **I may found the problem.** The corresponding **ThirdParty** file was not installed with OpenFOAM-v1812. I noticed the ThirdParty in the path above, but I cannot find it in the real path of my computer.

Did you solved your problem?

**Comment by jv79** [comment]
Hi,
I have the same error with 1912 version as can be seen in the file below.  
[wmakeAll.log](https://github.com/unicfdlab/libAcoustics/files/6260684/wmakeAll.log)

PS: Since I don't have admin privileges in this machine I had executed "SwitchDest" file before compile the library.

Thank you
