### ISSUE TITLE
Problems of Tutorials

### ISSUE THREAD

**Issue by Chansfoam** [unicfdlab/libAcoustics#23]
I have install the OpenFoam-v1812 from:
https://github.com/unicfdlab/OpenDTEF from branch v1812
and compile the libAcoustics -v1812 successfully, but I met some problems using tutorials, it reads:
--> FOAM FATAL IO ERROR: 
Entry 'reconstruct(T)' not found in dictionary "/home/nanbert/noise/monopole1D/system/fvSchemes.interpolationSchemes"

file: /home/nanbert/noise/monopole1D/system/fvSchemes.interpolationSchemes

From function const Foam::entry& Foam::dictionary::lookupEntry(const Foam::word&, Foam::keyType::option) const in file db/dictionary/dictionary.C at line 362.

FOAM exiting

And other bugs there. My computer is loaded with Ubuntu 19.04. Would it be a problems? 
Should I try version 4.1? 

Sincerely thanks for your work.

**Comment by VatutinKirill** [comment]
New version of tutorial for OpenFOAM-v1812 was upload. You can try it now.
