### ISSUE TITLE
Can't Compile OpenFOAM-1912

### ISSUE THREAD

**Issue by soydanahmet** [unicfdlab/libAcoustics#25]
Hi,

When i tried to compile your libAcoustics library using Openfoam v1912, i received an error because of using foam::complex class. When i solve this problem , another problem appears. The compiler asks for a file which is not does not exist.  As you can see in attached log file.

[log.wmakeAll.txt](https://github.com/unicfdlab/libAcoustics/files/4122701/log.wmakeAll.txt)

Could you please check my log file and advise for how can we solve this problem.

Best Regards.

**Comment by unicfdlab** [comment]
Hi, thank you for the feedback. I'll check issues and will write you back in several days. v1912 is still under verification.

**Comment by soydanahmet** [comment]
Hi, thank you for your attention. I sent wrong log file to you. The correct log file is attached.

[log.log](https://github.com/unicfdlab/libAcoustics/files/4122837/log.log)

**Comment by unicfdlab** [comment]
Checkout the branch again. Please, report if you find any issue

**Comment by soydanahmet** [comment]
I have compiled but i got a few warning messages.  You can see in attached wmakeAll.logfile.

[wmakeAll.log](https://github.com/unicfdlab/libAcoustics/files/4129534/wmakeAll.log)

After compiling, I've ran the dipole3D tutorial with 4 core and  i've received an error as you can se in attached rhoPimpleFoam.log file.

[rhoPimpleFoam.log](https://github.com/unicfdlab/libAcoustics/files/4129532/rhoPimpleFoam.log)

**Comment by unicfdlab** [comment]
Hi, there were some changes in OpenFOAM+1912 API. I have fixed the libAcoustics library, check again, please

**Comment by soydanahmet** [comment]
Hi, i have compiled successfully and dipole3D tutorial have ran without any error. Thank you for your attention again.
