### ISSUE TITLE
Place for libAcoustic

### ISSUE THREAD

**Issue by rclUPC** [unicfdlab/libAcoustics#26]
Hi,
It is not really important, but I had to make a small change in order to compile it with OpenFOAM-v1912. It couldn't write the `libAcoustic.so` because it was trying to do it in the system OF distribution. In order to install that in the user distribution, the line
`LIB = $(FOAM_LIBBIN)/libAcoustics`
should be changed by
`LIB = $(FOAM_USER_LIBBIN)/libAcoustics`
in the `lib/Make/files` file
With best regards
Robert

**Comment by unicfdlab** [comment]
Hi! yes this is an important issue, but we decided to put compiled solvers and libraries in $FOAM_APPBIN & $FOAM_LIBBIN intensionally. These programs and libraries are the part of DigiTEF, which must be installed in the OpenFOAM (OpenDTEF) directory

**Comment by unicfdlab** [comment]
And to fix this issue finally, I added script "SwitchDest" to root folder of branch. This script can be used to switch destination for compiled OpenFOAM sources
