### ISSUE TITLE
monopole-1D tutorial example

### ISSUE THREAD

**Issue by zeineldin117** [unicfdlab/libAcoustics#27]
I was trying to run one of tutorial case (monopole1D) and after setting mu to 1.8*e-5 instead the default value 0. I got an error message 
version libAcoustics-v1912
___________________________________________________________________________________________
--> FOAM FATAL IO ERROR:
Entry 'div(tauMC)' not found in dictionary "/nesi/nobackup/uoa00003/zein/noise/monopole1D/system/fvSchemes.divSchemes"

file: /nesi/nobackup/uoa00003/zein/noise/monopole1D/system/fvSchemes.divSchemes

    From function const Foam::entry& Foam::dictionary::lookupEntry(const Foam::word&, Foam::keyType::option) const
    in file db/dictionary/dictionary.C at line 380.
_____________________________________________________________________________________________________

**Comment by unicfdlab** [comment]
Hi, the case was prepared for inviscid the inviscid flow. If you want to turn-on the viscosity, you also need to define scheme settings for the viscous terms approximation.
