### ISSUE TITLE
Curle Analogy doesn't work

### ISSUE THREAD

**Issue by pvb22** [unicfdlab/libAcoustics#29]
I am using OpenFOAM v1912. Curle Analogy isn't working and I can't fix it. I can't see any tutorial that show how to use is. 

The problem is that the pressure fluctuations using the "cylinder" patch ( wall type) that have been calculated are always 0, even though the patch "cylinder" exist. Find the files that I'm using to set up Curle Analogy.

Thanks.

[curleTest-time.txt](https://github.com/unicfdlab/libAcoustics/files/4627600/curleTest-time.txt)
[curleControl.txt](https://github.com/unicfdlab/libAcoustics/files/4627601/curleControl.txt)
[commonSettings.txt](https://github.com/unicfdlab/libAcoustics/files/4627602/commonSettings.txt)

**Comment by unicfdlab** [comment]
Hi, thank you for the bug report.  We've fixed the bug. Can you try again?

**Comment by pvb22** [comment]
This time I am getting this error:

[4] --> FOAM FATAL ERROR:
[4] Could not find rho:rho
[4]
[4]     From function void Foam::functionObjects::forces::initialise()
[4]     in file forces/forces.C at line 235.
[4]
FOAM parallel run exiting

Seems that Curle Analogy needs a solver that calculates rho field? I don't understand why. Isn't Curle an analogy where density is considered constant?

**Comment by pvb22** [comment]
Now it works!!

Thanks.
