### ISSUE TITLE
Numerical scheme bugfix

### ISSUE THREAD

**Issue by engenegr** [unicfdlab/libAcoustics#3]
Acoustic pressure oscillations for 3d-monopole case.
Pure sin tone resulting in noisy p' tone at observers.
![pistonforcesplot](https://cloud.githubusercontent.com/assets/15425710/11540191/74aa7932-993c-11e5-8fca-13d770e8e813.png)
![curle90abcd](https://cloud.githubusercontent.com/assets/15425710/11540190/74a83be0-993c-11e5-9fcb-7e1fb1af2bf2.png)

**Comment by unicfdlab** [comment]
Issue was caused by incorrect interpolation from FVM mesh to surface. It was resolved later
