### ISSUE TITLE
Run FWH using own data

### ISSUE THREAD

**Issue by michaelmrq** [unicfdlab/libAcoustics#31]
Can I run only FWH using my own pre-simulated data? How can I input my values and run only FWH, also using my determined grid and FWH surface?

**Comment by unicfdlab** [comment]
Hello, today you can run FWH only together with the numerical simulation (simpleFoam, pisoFoam, or other solvers). We have in our plans the implementation of this feature in the middle of September  of 2020.

**Comment by unicfdlab** [comment]
Can you return to this issue somewhere in the 15th of Septemeber, 2020?

**Comment by michaelmrq** [comment]
Sure, thank you for sharing this info.

**Comment by michaelmrq** [comment]
Sure, thank you for sharing this info.
