### ISSUE TITLE
Resume acoustic collection properly

### ISSUE THREAD

**Issue by michaelmrq** [unicfdlab/libAcoustics#35]
Hi,

Everytime I run a couple of time steps collecting acoustic data and then I stop the simulation, my acoustic collection for the next time steps, when I resume the simulation, are not linked to the previous collection. It always starts from zero Pascal.

So, how do I properly resume the acoustic collection for the next saved timestep? Lets say, I started on t = 1 second then I stop on t = 1.5 second and I want to resume the simulation and the acoustic collection from here without any divergences.

Thank you.

**Comment by unicfdlab** [comment]
Hi, to add resume capability, we need to implement reading and writing of all information on FWH surface. We plan to add these feature till the end of the year. After this, the implementation of restart/resume should not be difficult

**Comment by michaelmrq** [comment]
Okay.

Thank you for the support provided and I hope these and other new features get ready soon. Until now, it's been a great work from you all.

Best Regards.

**Comment by xevious54** [comment]
> Hi, to add resume capability, we need to implement reading and writing of all information on FWH surface. We plan to add these features till the end of the year. After this, the implementation of restart/resume should not be difficult

Was this implemented yet in the new versions?

**Comment by nainapisharoti** [comment]
I have the same issue as well. It would be great if this issue gets resolved. 

>
