### ISSUE TITLE
 I have noticed that your code has “GTFormulation”. I wonder what GTFormulation is. Could you recommend me some paper about this formulation?

### ISSUE THREAD

**Issue by lianjieyu** [unicfdlab/libAcoustics#37]

**Comment by unicfdlab** [comment]
Hi, I think the recipe is simple:
Type in google: FWH GT formulation 

The first reference gives: https://www.researchgate.net/publication/268581582_A_Ffowcs_Williams_-_Hawkings_Solver_for_Lattice-Boltzmann_Based_Computational_Aeroacoustics

**Comment by lianjieyu** [comment]
Thank you! Your reply is really helpful.

**Comment by lianjieyu** [comment]
Thank you for your reply. Your advice is really helpful.

 

Sincerely,

Yu Lianjie

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 UniCFD
发送时间: 2020年8月6日 16:13
收件人: unicfdlab/libAcoustics <libAcoustics@noreply.github.com>
抄送: lianjieyu <leo_yates@163.com>; Author <author@noreply.github.com>
主题: Re: [unicfdlab/libAcoustics] I have noticed that your code has “GTFormulation”. I wonder what GTFormulation is. Could you recommend me some paper about this formulation? (#37)

 

Hi, I think the recipe is simple:
Type in google: FWH GT formulation

The first reference gives: https://www.researchgate.net/publication/268581582_A_Ffowcs_Williams_-_Hawkings_Solver_for_Lattice-Boltzmann_Based_Computational_Aeroacoustics
