### ISSUE TITLE
deltaT in controDict will affact the result seriously.

### ISSUE THREAD

**Issue by lianjieyu** [unicfdlab/libAcoustics#39]
When calculating the flow around the cylinder, I found that different deltaT will have a different amplitude in dipoleFwhFarassatTest-time.dat which has a serious impact. Specifically, every time deltaT is reduced by 1/10, the noise amplitude increases by 10 times. May I know what is the reason?

**Comment by unicfdlab** [comment]
Hi, tried **monopole2D** test case with two time steps 2.5e-6 and 2.5e-7 and amplitudes of pressure are the same. Can you write here which solver are using? Which BCs and ICs are set in your case?

**Comment by lianjieyu** [comment]
May I have your e-mail, and I will send you my Complete case folder？My solver is a modified pimpleFoam, which outputs a constant rho field. My boundary conditions and initial conditions are as follows:

FoamFile
{
    version     2.0;
    format      ascii;
    class       volScalarField;
    location    "0";
    object      nut;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 2 -1 0 0 0 0];

internalField   uniform 1.0e-05;

boundaryField
{
    sphere
    {
        type            nutUSpaldingWallFunction;
        value           $internalField;
    }

    inlet
    {
        type            calculated;
        value           $internalField;
    }

    "(outlet|top|bottom)"
    {
        type            calculated;
        value           $internalField;
    }

    frontAndBack
    {
        type            empty;
    }
}

FoamFile
{
    version     2.0;
    format      ascii;
    class       volScalarField;
    location    "0";
    object      nuTilda;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 2 -1 0 0 0 0];

internalField   uniform 1e-05;

boundaryField
{
    sphere
    {
        type            zeroGradient;
        value           $internalField;
    }

    inlet
    {
        type            fixedValue;
        value           $internalField;
    }

    outlet
    {
        type            inletOutlet;
        inletValue      $internalField;
        value           $internalField;
    }

    "(top|bottom)"
    {
        type            zeroGradient;
    }

    frontAndBack
    {
        type            empty;
    }
}

FoamFile
{
    version     2.0;
    format      ascii;
    class       volScalarField;
    object      p;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 2 -2 0 0 0 0];

internalField   uniform 0;

boundaryField
{
    sphere
    {
        type            zeroGradient;
    }

    inlet
    {
        type            zeroGradient;
    }

    outlet
    {
        type            fixedValue; // totalPressure;
        rho             none;
        psi             none;
        p0              $internalField;
        gamma           1;
        value           $internalField;
    }

    "(top|bottom)"
    {
        type            zeroGradient;
    }

    frontAndBack
    {
        type            empty;
    }
}

FoamFile
{
    version     2.0;
    format      ascii;
    class       volVectorField;
    object      U;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 1 -1 0 0 0 0];

internalField   uniform (0.025 0 0);

boundaryField
{
    sphere
    {
        type            fixedValue;
        value           uniform (0 0 0);
    }

    inlet
    {
        type            fixedValue;
        value           uniform (0.025 0 0);
    }

    outlet
    {
        type            inletOutlet;
        value           uniform (0 0 0);
        inletValue      uniform (0 0 0);
    }

    "(top|bottom)"
    {
        type            slip;
    }

    frontAndBack
    {
        type            empty;
    }
}

**Comment by unicfdlab** [comment]
Hey,

it's better to post all information here -- in case someone would experience the same problem, then he could use this information.

**Comment by unicfdlab** [comment]
> My solver is a modified pimpleFoam, which outputs a constant rho field.

Since **pimpleFoam** is incompressible, then the the decrease in time step would lead to increase of pressure growth during initial phase of simulation. After some time, everything should be OK.

Also I would recommend to use **totalPressure** for **p** and **zeroGradient** for **U** on outlet -- this should increase overall stability

**Comment by lianjieyu** [comment]
OK. I use labAcoustic of 1912, compiled and run on of2006. First compile the testPimpleFoam in the compressed package (remember wclean before compiling), and then run the Allrun script in the vortexShed folder.
[libAcoustic_vortexShed.zip](https://github.com/unicfdlab/libAcoustics/files/5150350/libAcoustic_vortexShed.zip)

**Comment by lianjieyu** [comment]
Thank you very much. I will try to simulate this  up to 100 seconds time. Thank you for your help!

**Comment by unicfdlab** [comment]
> I will try to simulate this up to 100 seconds time.

I would recommend to select simulation time from the geometry and inlet velocity. For example, if the domain length is **L** and inlet velocity is **Uin**, then the minimum simulation time should be **2*Lin/Uin**

**Comment by lianjieyu** [comment]
Thank you so much! It's so kind of you!

**Comment by lianjieyu** [comment]
By the way, I wonder how to use Curle in labAcoustic? I changed the type in the fwhControl file from FfowcsWilliamsHawkings to Curle, but it will report an error saying "Dynamic pressure is expected but kinematic is provided." How can I use Curle type?

**Comment by unicfdlab** [comment]
> By the way, I wonder how to use Curle in labAcoustic? I changed the type in the fwhControl file from FfowcsWilliamsHawkings to Curle, but it will report an error saying "Dynamic pressure is expected but kinematic is provided." How can I use Curle type?

I think, this is caused by outlet BCs with total pressure:
> outlet
{
    type            fixedValue; // totalPressure;
    rho             none;
    psi             none;
    p0              $internalField;
    gamma           1;
    value           $internalField;
}

Can you upload here your test case?

**Comment by lianjieyu** [comment]
I'm sorry I didn't read the website before, so I couldn't reply to you in time. Thank you for your answer. The Curle method seems to be available now, no errors are reported. But there is still a problem, no matter which method I use, the sound pressure time history result file in the acoustic folder is always called "dipoleFwhFarassatTest.dat". Is there any way to modify the name of the result file? Because this is not very convenient.

**Comment by unicfdlab** [comment]
Hi, you must change name of the dictionary, where Acoustic Analogy is define:

> dipoleFwhFarassatTest
{
        type            FfowcsWilliamsHawkings;
        #include        "commonSettings";
        patches ("sphere");
..............
}

**dipoleFwhFarassatTest** is the name of dictionary

**Comment by lianjieyu** [comment]
Thank you very much! Tests have proved that your method is very effective!

**Comment by chen0mou0mou** [comment]
> > I will try to simulate this up to 100 seconds time.
> 
> I would recommend to select simulation time from the geometry and inlet velocity. For example, if the domain length is **L** and inlet velocity is **Uin**, then the minimum simulation time should be **2*Lin/Uin**

Hi，

Is the 2*Lin/Uin the recommended running time for the CFD case or the libacoustics? I have run a case for 10*L/Uin without libacoustics. Could I continue to run this case with libacoutics for another time smaller than 2Lin/Uin to get the acoustic pressure?

Regards,
Guanjiang

**Comment by eacfd** [comment]
Yes, you can continue the case with libAcoustics. The calculation time will depend on the required resolution of the spectrum.
