### ISSUE TITLE
The amount of saved data in dipoleFwhFarassatTest-time.dat file in acousticData is limited

### ISSUE THREAD

**Issue by lianjieyu** [unicfdlab/libAcoustics#40]
Hello! I found that the number of time steps saved in the dipoleFwhFarassatTest-time.dat file is always relatively small. For example, my noise calculation time is 1-2s, but the time result saved in the dat file is only 1-1.02. Although it is still calculating after 1.02s, the dat file does not continue to calculate the noise result. How can I keep more data results?

**Comment by unicfdlab** [comment]
Hi, please check values of keywords

>   timeStart       0; //When to start sampling
    timeEnd         1; //When to stop sampling

**Comment by lianjieyu** [comment]
Thank you very much! But I have set timeStart as1 and timeEnd as 200. The truth is that the dipoleFwhFarassat-time.dat still ends at around 1.02s. This is really confusing.

**Comment by unicfdlab** [comment]
Can you attach your settings files?

**Comment by lianjieyu** [comment]
OK! This is my test case.
[test.zip](https://github.com/unicfdlab/libAcoustics/files/5347424/test.zip)

**Comment by unicfdlab** [comment]
And do you see output in stdio, where solution log OpenFOAM usually shows?
Can you post here the part of the solution log after 1.02s ?

**Comment by lianjieyu** [comment]
I am so sorry. I realized that the case has stopped after 1.02s. Thank you for your tips!

**Comment by unicfdlab** [comment]
Ok, I hope you will do the good and interesting research with libAcoustics!
