### ISSUE TITLE
problem making openfoam-3.0.0

### ISSUE THREAD

**Issue by chancesFOAM** [unicfdlab/libAcoustics#41]
I want to test the case "cylinder2D" in openfoam-3.0.0/case, but it cannot run in the openfoam-4.1 version. Therefore I use OpenFOAM-3.0.0 and now I want to make the package. It doesn't contain a Allwmake script, so I directly type "wmake" and run it. I reads:
`make: *** No rule to make target `Make/linux64GccDPInt32Opt/soundObserver/SoundObserver.C.dep', needed by `Make/linux64GccDPInt32Opt/soundObserver/SoundObserver.o'.  Stop.
`
Please tell me how to make it or how to use the cylinder case in other version. I've test through all other version and they fail. 
Sincerely, thanks for your attention.

**Comment by unicfdlab** [comment]
Don't you forget to type 'wclean' before running wmake?

**Comment by chancesFOAM** [comment]
yeah, it works, thank you!
sorry for my ignorance. I'm new for openfoam.

**Comment by unicfdlab** [comment]
Nevertheless, I would recommend to use versions for OpenFOAM+1912 or OpenFOAM+1812, because  many bugs were fixed since OpenFOAM-3.0

**Comment by chancesFOAM** [comment]
thanks for your recommendation. The main problem of mine is that I could not find a case that used in incompressible situation except in your OpenFOAM+3. 
By the way, I encountered some problems using 1812 when applying it to an incompressible cylinder flow.  It said "rho cannot found". 
Other problems may raise in parallelProcess. I don't know how to use it. I always run the process without it. So all I need maybe just a simplest case so that I can build up on it.
Thanks again. libAcoustic is the only FWH processor in OpenFOAM that I can find in github or the whole internet. I believe it would help me a lot.

**Comment by unicfdlab** [comment]
libAcoustics uses libforces to calculate forces acting on the surfaces. Thus, most changes in libAcousitcs syntax are due to changes in libforces syntax. You can see tutorials for libforces (or libforceCoeffs) to understand what's wrong with libAcoustics.

For the density, you must type:

rho rhoInf;
rhoInf 1;

**Comment by chen0mou0mou** [comment]
> Nevertheless, I would recommend to use versions for OpenFOAM+1912 or OpenFOAM+1812, because many bugs were fixed since OpenFOAM-3.0

How about OpenFOAM-4.1? I am using libacoustics OpenFOAM-4.1 version in the OpenFOAM 6.0.
Thanks.
