### ISSUE TITLE
problem using v1912 version

### ISSUE THREAD

**Issue by chancesFOAM** [unicfdlab/libAcoustics#42]
I use the newest version 1912 and trying a incompressible turbulence cylinder case.
First, I use the curleControl file but it reads "Entry 'patches' not found in dictionary". 
Then I use the fwhControl file, but it says "rho cannot found", because there is inheriently no rho file in a incompressible case. 
I tried "another" fwhControl file from the version 3.0, it can run but there is no output of fft file.
However, I noticed that other cases in the tutorials have no rho file, either.
I don't know how to do. I attach my file so that you might check. 
THANKS!
[cylinder2D.zip](https://github.com/unicfdlab/libAcoustics/files/5408214/cylinder2D.zip)

**Comment by unicfdlab** [comment]
in the fwhControl file:

> rho rhoInf;
rhoInf 1.2;

Delete also rhoName and rhoRef -- they obsolete

**Comment by chancesFOAM** [comment]
yeah I have deleted them.
Nevertheless, I still error: Entry 'rhoInf' not found in dictionary ...

**Comment by unicfdlab** [comment]
> yeah I have deleted them.
> Nevertheless, I still error: Entry 'rhoInf' not found in dictionary ...

Then add rhoInf entry

**Comment by chancesFOAM** [comment]
Then it said “request for volScalarField rho from objectRegistry”
it's so werid that other cases like monopole2D can run...

**Comment by unicfdlab** [comment]
add
>rho rhoInf;

**Comment by chancesFOAM** [comment]
Ok, i make it.
THANKS!
