### ISSUE TITLE
FW-H surfaces velocity

### ISSUE THREAD

**Issue by VamosZhi** [unicfdlab/libAcoustics#43]
Hi, I have simple questions, maybe someone could help me?
If I have a fixed patches in moving flow, and I want to use Farassat’s formulation 1A method, I noticed the paper of the original codes said that "Farassat’s formulation 1A14, 15 is implemented to predict the noise generated by an acoustic source moving in a fluid at rest, and measured at a stationary observer located in the far-field." see paper DOI:10.2514/6.2010-3711, 
But we also need to set the U0 as zero while using Farassat’s formulation 1A, so how to express the relative velocity between inflow and the FW-H surfaces or observers? Do it mean that I set U0=0, and set the Ufw-h to the negative inflow velocity. But how do I express the relative velocity between inflow and observers?
Many thanks!
ZHI

**Comment by chancesFOAM** [comment]
Same question. Do you solve this yet?

**Comment by unicfdlab** [comment]
Hi, U0 is used when you move STL surface with constant velocity. However, if you use dynamic mesh and set your FWH surface  as moving patch , then you get Farassat 1A formulation for non-permeable moving surface.

**Comment by VamosZhi** [comment]
> Hi, U0 is used when you move STL surface with constant velocity. However, if you use dynamic mesh and set your FWH surface as moving patch , then you get Farassat 1A formulation for non-permeable moving surface.

Thanks for your reply!
I have two examples with questions here:
1. The three blades are rotating with rpm 10 and radius 1 m, with inlow velocity of 1 m/s, how do I set formulationType, U0, Ufwh respectively?
2. The cylinder is in linear oscillation, with inlow velocity of 1m/s, how do I set formulationType, U0, Ufwh respectively?
Best,

**Comment by unicfdlab** [comment]
> The three blades are rotating with rpm 10 and radius 1 m, with inlow velocity of 1 m/s, how do I set formulationType, U0, Ufwh respectively?
Set FWH control surface to patch encompassing these 3 blades, `Ufwh		(.0 .0 .0);`, `nonUniformSurfaceMotion true;`  `formulationType Farassat1AFormulation;`

**Comment by unicfdlab** [comment]
> The cylinder is in linear oscillation, with inlow velocity of 1m/s, how do I set formulationType, U0, Ufwh respectively?
Best,

Set FWH control surface to the surface encompassing region in which cylinder translates and set `fwh (.0 .0 .0);`, `nonUniformSurfaceMotion false;` `formulationType Farassat1AFormulation;`

**Comment by unicfdlab** [comment]
> The cylinder is in linear oscillation, with inlow velocity of 1m/s, how do I set formulationType, U0, Ufwh respectively?

**OR:** Set FWH control surface to the surface encompassing patch of the cylinder translates and set `fwh (.0 .0 .0);`, `nonUniformSurfaceMotion true;` `formulationType Farassat1AFormulation;`

**Comment by VamosZhi** [comment]
> > The cylinder is in linear oscillation, with inlow velocity of 1m/s, how do I set formulationType, U0, Ufwh respectively?
> 
> **OR:** Set FWH control surface to the surface encompassing patch of the cylinder translates and set `fwh (.0 .0 .0);`, `nonUniformSurfaceMotion true;` `formulationType Farassat1AFormulation;`

Many thanks for your attention!
According to your reply, I just need to set 'nonUniformSurfaceMotion true', and no detailed information for body motion is needed in FW-H solver parameters setting. Am I right?
Best,

**Comment by unicfdlab** [comment]
> > > The cylinder is in linear oscillation, with inlow velocity of 1m/s, how do I set formulationType, U0, Ufwh respectively?
> > 
> > 
> > **OR:** Set FWH control surface to the surface encompassing patch of the cylinder translates and set `fwh (.0 .0 .0);`, `nonUniformSurfaceMotion true;` `formulationType Farassat1AFormulation;`
> 
> Many thanks for your attention!
> According to your reply, I just need to set 'nonUniformSurfaceMotion true', and no detailed information for body motion is needed in FW-H solver parameters setting. Am I right?
> Best,

Yes, if you select patch which encompasses the moving body as control surface

**Comment by VamosZhi** [comment]
Thanks! Excuse me for too many questions.
I have last question here. You have two setting method for my 'cylinder linear oscillation' examples. I try to figure out the differeces between:
1. Set FWH control surface to the surface encompassing region in which cylinder translates
2. Set FWH control surface to the surface encompassing patch of the cylinder translates
But I didn't make it clear. Could you help me with this?
Best,

**Comment by VamosZhi** [comment]
> > > > The cylinder is in linear oscillation, with inlow velocity of 1m/s, how do I set formulationType, U0, Ufwh respectively?
> > > 
> > > 
> > > **OR:** Set FWH control surface to the surface encompassing patch of the cylinder translates and set `fwh (.0 .0 .0);`, `nonUniformSurfaceMotion true;` `formulationType Farassat1AFormulation;`
> > 
> > 
> > Many thanks for your attention!
> > According to your reply, I just need to set 'nonUniformSurfaceMotion true', and no detailed information for body motion is needed in FW-H solver parameters setting. Am I right?
> > Best,
> 
> Yes, if you select patch which encompasses the moving body as control surface

Thanks! Excuse me for too many questions.
I have last question here. You have two setting method for my 'cylinder linear oscillation' examples. I try to figure out the differeces between:

Set FWH control surface to the surface encompassing region in which cylinder translates
Set FWH control surface to the surface encompassing patch of the cylinder translates
But I didn't make it clear. Could you help me with this?
Best,

**Comment by unicfdlab** [comment]
In the first case, FWH control surface is steady and permeable and it encompasses the whole region where cylinder oscillates (cylinder doesn't cross or touch this surface). In the second case the FWH control surface coincides with the surface of the cylinder - it is not permeable, but moves together with the cylinder.

**Comment by chen0mou0mou** [comment]
> > The cylinder is in linear oscillation, with inlow velocity of 1m/s, how do I set formulationType, U0, Ufwh respectively?
> > Best,
> 
> Set FWH control surface to the surface encompassing region in which cylinder translates and set `fwh (.0 .0 .0);`, `nonUniformSurfaceMotion false;` `formulationType Farassat1AFormulation;`

Hi，

A little question. If we set nonUniformSurfaceMotion false, shall we set a value for U0? How to set it? U0（0 0 0) for Farassat1AFormulation?

Regards,
Guanjiang

**Comment by chakshudeora** [comment]
> > The three blades are rotating with rpm 10 and radius 1 m, with inlow velocity of 1 m/s, how do I set formulationType, U0, Ufwh respectively?
> 
> Set FWH control surface to patch encompassing these 3 blades, `Ufwh (.0 .0 .0);`, `nonUniformSurfaceMotion true;` `formulationType Farassat1AFormulation;`

This is true for the dynamic mesh, right? How to simulate the same problem of 3 propeller blades rotating, but for rotation rather than using dynamic mesh, I am using MRF to simulate the effect of rotation. What will be the values of U0, Ufwh? 

I would really appreciate the help.
Regards,
Chakshu

**Comment by chen0mou0mou** [comment]
> > > The three blades are rotating with rpm 10 and radius 1 m, with inlow velocity of 1 m/s, how do I set formulationType, U0, Ufwh respectively?
> > 
> > 
> > Set FWH control surface to patch encompassing these 3 blades, `Ufwh (.0 .0 .0);`, `nonUniformSurfaceMotion true;` `formulationType Farassat1AFormulation;`
> 
> This is true for the dynamic mesh, right? How to simulate the same problem of 3 propeller blades rotating, but for rotation rather than using dynamic mesh, I am using MRF to simulate the effect of rotation. What will be the values of U0, Ufwh?
> 
> I would really appreciate the help.
> Regards,
> Chakshu

In this case, U0 may be zero, and Ufwh may be set the rotating speed.

**Comment by chakshudeora** [comment]
> > > > The three blades are rotating with rpm 10 and radius 1 m, with inlow velocity of 1 m/s, how do I set formulationType, U0, Ufwh respectively?
> > > 
> > > 
> > > Set FWH control surface to patch encompassing these 3 blades, `Ufwh (.0 .0 .0);`, `nonUniformSurfaceMotion true;` `formulationType Farassat1AFormulation;`
> > 
> > 
> > This is true for the dynamic mesh, right? How to simulate the same problem of 3 propeller blades rotating, but for rotation rather than using dynamic mesh, I am using MRF to simulate the effect of rotation. What will be the values of U0, Ufwh?
> > I would really appreciate the help.
> > Regards,
> > Chakshu
> 
> In this case, U0 may be zero, and Ufwh may be set the rotating speed.

@unicfdlab Can you please confirm this? Is it even possible to use libacoustics with MRF?
