### ISSUE TITLE
How to implement a 2D FW-H permeable surface in a 2D case?

### ISSUE THREAD

**Issue by chancesFOAM** [unicfdlab/libAcoustics#44]
Hi! I have some questions about the STL file in monopoly3D/constant/triSurface:
1. Is it created by some modeling software like Catia or proE?
2. How can I implement it in a 2D case in openfoam? 
Thanks! 
Lawrence

**Comment by unicfdlab** [comment]
1. Yes, it is created using SALOME package
2. Just make piece of STL, which corresponds to the depth of 2D computational domain in OpenFOAM

**Comment by chen0mou0mou** [comment]
> Hi! I have some questions about the STL file in monopoly3D/constant/triSurface:
> 
> 1. Is it created by some modeling software like Catia or proE?
> 2. How can I implement it in a 2D case in openfoam?
>    Thanks!
>    Lawrence

Hi Lawrence,

If I am not wrong, Openfoam doesn't have the theoretical 2D simulation. It will give a depth value in the third direction, so we need set dRef in libacoustics for the 2D case. You can check the depth of your 2D case in constant/polyMesh/points.
