### ISSUE TITLE
Is there any way to select sampling surfaces other than 'patch'?

### ISSUE THREAD

**Issue by innykim** [unicfdlab/libAcoustics#46]
I am trying to select a sampling surface that I did not create as a 'patch' in the mesh generating step. 
I found something like 'sampledTriSurfaceMesh' and tried a bit with an 'STL' file but keeps giving me errors like Foam::sigFpe::sigHandler(int)
Is there any way to select sampling surfaces other than 'patch'?

**Comment by unicfdlab** [comment]
Hi, 

yes, with FWH analogy you can use STL or OBJ files to specify sampling surface. Which analogy do you use?

**Comment by innykim** [comment]
I really appreciate your support!

I am using FWH analogy and actually, I found a way to use a STL file to create a sample surface.
It looks fine but I am not sure whether I am using it correctly.
This is my fwh setting file.
I am using a STL file for sampling surface.. but what is 'patches' in the setting file?
I found that it must be specified.
Is it just a placeholder if I use the STL file to create a sampling surface?
![image](https://user-images.githubusercontent.com/78628355/107298701-35db7180-6ab9-11eb-9df7-16cdbb551ce5.png)

And also, what is the appropriate resolution of the STL file?
I created the STL file with the same resolution as the fluid mesh size, but I found out that it takes so long time to sample.

Anyway, I am using this great library thanks to your support.

**Comment by unicfdlab** [comment]
Hi, if you use STL surfaces, then you can set 
`patches ();`

You can calculate noise from several surfaces in one run. This will allow you to compare response from different surfaces and, as the consequence, to assess sensitivity of your model.

> And also, what is the appropriate resolution of the STL file?

I would recommend to try measuring noise from STL surfaces with different resolution and distance to source/observer to get reliable predictions
