### ISSUE TITLE
what should be the value of U0 in case of Farassat1AFormulation & GTFormulation and how the retarded time is calculated (fixedResponceDelay false;)

### ISSUE THREAD

**Issue by zeineldin117** [unicfdlab/libAcoustics#50]
I want to ask about FWH acoustic analogy, there are two formulations for FWH (Farassat1AFormulation-GTFormulation)

1-In the case of a stationary source and observer, with flow moving with constant velocity (20 m/s)
for  Farassat1AFormulation: Ufwh (0 0 0)
                                              U0    (0 0 0)
for  GTFormulation              :Ufwh (0 0 0)
                                              U0    (20 0 0)

2- In the case of using  GTFormulation for flow with stationary source and observer, while the flow is entering the flow domain at an angle (10 degrees), The reference frame should be rotated to satisfy  U0    (20 0 0). What should be changed in the input files for that case?

3- In case of using fixedResponceDelay  false;
that means that the ResponseDelay will be calculated for every surface (ds) on the noise source surface, am I right?
In that case, I was reading the code, but I could not understand how that time is calculated.

**Comment by eacfd** [comment]
Dear Zein!

> In the case of a stationary source and observer, with flow moving with constant velocity (20 m/s) for Farassat1AFormulation: Ufwh (0 0 0) U0 (0 0 0) for GTFormulation :Ufwh (0 0 0) U0 (20 0 0)

Yes, its correct.

>In the case of using GTFormulation for flow with stationary source and observer, while the flow is entering the flow domain at an angle (10 degrees), The reference frame should be rotated to satisfy U0 (20 0 0). What should be changed in the input files for that case?

There are two ways. The first one is to rotate the wall by 10 degrees. The second is set U0 equal to (U*cos(a) U*sin(a) 0).

> In case of using fixedResponceDelay false; that means that the ResponseDelay will be calculated for every surface
(ds) on the noise source surface, am I right? In that case, I was reading the code, but I could not understand how
that time is calculated.

If fixedResponceDelay is false, the time is equal to retarted time that calculated as t = r/c. Where r is a distance from each dS to observer. See https://github.com/unicfdlab/libAcoustics/issues/48
