### ISSUE TITLE
Flow past a cylidner_FWH_curle

### ISSUE THREAD

**Issue by chen0mou0mou** [unicfdlab/libAcoustics#53]
Could anyone help me check my case set? I have used the curle method in the flow past a cylinder case to get a relatively good acoustic pressure result. For the FWH method, if the cylinder surface is chosen as the control surface, the FWH result is very close to the curle result. But if another control surface that contains more areas is used, the FWH result does not capture the noise spectra correctly. I use the libacoustic OpenFOAM4.1 version in the OpenFOAM 6. The formulation we use is Farassat1A, and the GT_formulation shows similar results. As it is a wind-tunnel problem(the model and observer are static), the U_0 is (0 0 0), U_fwh is (0 0 0), nonUniformSurfaceMotion is  false. The fixedResponseDelay seems to have little influence on the results. I am running a case with 'patches (); source cells;' instead of 'patches (CYLINDER);'. Is there something wrong with my set? What should I change?

Thanks!

[fwh for flow past a cylinder2.pdf](https://github.com/unicfdlab/libAcoustics/files/6390790/fwh.for.flow.past.a.cylinder2.pdf)

**Comment by ThanatSAISA** [comment]
Hey, What if i don,t have a second control surface, is it still works ?.

**Comment by eacfd** [comment]
> Could anyone help me check my case set? I have used the curle method in the flow past a cylinder case to get a relatively good acoustic pressure result. For the FWH method, if the cylinder surface is chosen as the control surface, the FWH result is very close to the curle result. But if another control surface that contains more areas is used, the FWH result does not capture the noise spectra correctly. I use the libacoustic OpenFOAM4.1 version in the OpenFOAM 6. The formulation we use is Farassat1A, and the GT_formulation shows similar results. As it is a wind-tunnel problem(the model and observer are static), the U_0 is (0 0 0), U_fwh is (0 0 0), nonUniformSurfaceMotion is false. The fixedResponseDelay seems to have little influence on the results. I am running a case with 'patches (); source cells;' instead of 'patches (CYLINDER);'. Is there something wrong with my set? What should I change?

Dear Chen!
Did you compare aerodynamic characteristics such as mean and RMS values of cd, cL, and Strouhal number with experimental data? You have poor mesh resolution or dissipative numerical scheme if another control surface doesn't capture noise spectra. 
Also, I recommend using the OpenFOAM-v1912 version of the library (see branch digitef-dev-1912) as some bugs were fixed there.

Regards,
AE

**Comment by chen0mou0mou** [comment]
> Hey, What if I don't have a second control surface, is it still works ?.
> May I look at your file that you simulate , I stuck with how to use it correctly.
> Thank you

Hi，

Could you share your set file with me? I will compare your set with mine, and tell you the difference.

**Comment by chen0mou0mou** [comment]
> > Could anyone help me check my case set? I have used the curle method in the flow past a cylinder case to get a relatively good acoustic pressure result. For the FWH method, if the cylinder surface is chosen as the control surface, the FWH result is very close to the curle result. But if another control surface that contains more areas is used, the FWH result does not capture the noise spectra correctly. I use the libacoustic OpenFOAM4.1 version in the OpenFOAM 6. The formulation we use is Farassat1A, and the GT_formulation shows similar results. As it is a wind-tunnel problem(the model and observer are static), the U_0 is (0 0 0), U_fwh is (0 0 0), nonUniformSurfaceMotion is false. The fixedResponseDelay seems to have little influence on the results. I am running a case with 'patches (); source cells;' instead of 'patches (CYLINDER);'. Is there something wrong with my set? What should I change?
> 
> Dear Chen!
> Did you compare aerodynamic characteristics such as mean and RMS values of cd, cL, and Strouhal number with experimental data? You have poor mesh resolution or dissipative numerical scheme if another control surface doesn't capture noise spectra.
> Also, I recommend using the OpenFOAM-v1912 version of the library (see branch digitef-dev-1912) as some bugs were fixed there.
> 
> Regards,
> AE

Hi,

Thank you for your help! We have compared the pressure coefficients Cp，PSD of our CFD results with the experimental data. The results are well.  Our mesh resolution is also thought good enough. The influence of the dissipative numerical scheme is not tested. Now, I am trying the OpenFOAM-v1912 version.

Regards,
Guanjiang

**Comment by ThanatMU** [comment]
> > Hey, What if I don't have a second control surface, is it still works ?.
> > May I look at your file that you simulate , I stuck with how to use it correctly.
> > Thank you
> 
> Hi，
> 
> Could you share your set file with me? I will compare your set with mine, and tell you the difference.

[Cylinder.zip](https://github.com/unicfdlab/libAcoustics/files/6493988/Cylinder.zip)
I try to validate with The paper named Prediction of Flow induced sound  generated by cross flow past finite length circular cylinder.
My peak  freq is not correct.

**Comment by ThanatSAISA** [comment]
Afraid that one of the reasons is mesh


ในวันที่ จ. 17 พ.ค. 2021 เวลา 20:17 Zamfx1230 ***@***.***>
เขียนว่า:

**Comment by ThanatSAISA** [comment]
another question, What if i want to use .obj file at the surface selection in FWH analogy. I found that it is possible to convert blockMesh into .obj but I confused that, was the FWH know that i want to use only the cylinder not the entire mesh.

**Comment by chen0mou0mou** [comment]
> > > Hey, What if I don't have a second control surface, is it still works ?.
> > > May I look at your file that you simulate , I stuck with how to use it correctly.
> > > Thank you
> > 
> > 
> > Hi，
> > Could you share your set file with me? I will compare your set with mine, and tell you the difference.
> 
> [Cylinder.zip](https://github.com/unicfdlab/libAcoustics/files/6493988/Cylinder.zip)
> I try to validate with The paper named Prediction of Flow induced sound generated by cross flow past finite length circular cylinder.
> My peak freq is not correct. Also, Force collecting (post processing)

[curle.txt](https://github.com/unicfdlab/libAcoustics/files/6497160/curle.txt)
 Hi,

Your curle set misses interpolationScheme and surface set. I make a few changes, and you can run it to see whether the result will be improved.

Regards,
Guanjiang

**Comment by chen0mou0mou** [comment]
> tion, What if i want to use .obj file at the surface selection in FWH analogy. I found that it is possible to convert blockMesh into .obj but I confused that, was the FWH know that i want to use only the cylinder not the entire mesh.

I don't know. I still use the trisurface. You can begin another issue as this problem is very important.

**Comment by chen0mou0mou** [comment]
> > Could anyone help me check my case set? I have used the curle method in the flow past a cylinder case to get a relatively good acoustic pressure result. For the FWH method, if the cylinder surface is chosen as the control surface, the FWH result is very close to the curle result. But if another control surface that contains more areas is used, the FWH result does not capture the noise spectra correctly. I use the libacoustic OpenFOAM4.1 version in the OpenFOAM 6. The formulation we use is Farassat1A, and the GT_formulation shows similar results. As it is a wind-tunnel problem(the model and observer are static), the U_0 is (0 0 0), U_fwh is (0 0 0), nonUniformSurfaceMotion is false. The fixedResponseDelay seems to have little influence on the results. I am running a case with 'patches (); source cells;' instead of 'patches (CYLINDER);'. Is there something wrong with my set? What should I change?
> 
> Dear Chen!
> Did you compare aerodynamic characteristics such as mean and RMS values of cd, cL, and Strouhal number with experimental data? You have poor mesh resolution or dissipative numerical scheme if another control surface doesn't capture noise spectra.
> Also, I recommend using the OpenFOAM-v1912 version of the library (see branch digitef-dev-1912) as some bugs were fixed there.
> 
> Regards,
> AE

Sorry,

I don't find the digitef-dev-1912 branch and also the OpenFOAM-v1912 version libacoustics. I just get a source in https://zenodo.org/record/3878439#.YKPXCahKiUk.

Is that right?

Regards,
Guanjiang

**Comment by chen0mou0mou** [comment]
> > Could anyone help me check my case set? I have used the curle method in the flow past a cylinder case to get a relatively good acoustic pressure result. For the FWH method, if the cylinder surface is chosen as the control surface, the FWH result is very close to the curle result. But if another control surface that contains more areas is used, the FWH result does not capture the noise spectra correctly. I use the libacoustic OpenFOAM4.1 version in the OpenFOAM 6. The formulation we use is Farassat1A, and the GT_formulation shows similar results. As it is a wind-tunnel problem(the model and observer are static), the U_0 is (0 0 0), U_fwh is (0 0 0), nonUniformSurfaceMotion is false. The fixedResponseDelay seems to have little influence on the results. I am running a case with 'patches (); source cells;' instead of 'patches (CYLINDER);'. Is there something wrong with my set? What should I change?
> 
> Dear Chen!
> Did you compare aerodynamic characteristics such as mean and RMS values of cd, cL, and Strouhal number with experimental data? You have poor mesh resolution or dissipative numerical scheme if another control surface doesn't capture noise spectra.
> Also, I recommend using the OpenFOAM-v1912 version of the library (see branch digitef-dev-1912) as some bugs were fixed there.
> 
> Regards,
> AE

Hi,

I have uploaded my system set. Do you think my scheme and solver set are suitable for the libacoustics.
[system.zip](https://github.com/unicfdlab/libAcoustics/files/6538019/system.zip)

**Comment by unicfdlab** [comment]
The linear scheme for convective term div(phi, U) is not good choice because it leads to oscillation in the solution. Try to use LUST or our schemes https://github.com/unicfdlab/libSchemes for LES turbulence model.

**Comment by chen0mou0mou** [comment]
Thank you, I will try it.

**Comment by chen0mou0mou** [comment]
Thanks
