### ISSUE TITLE
Can The microphone  locate outside the Computational domain? If  possible, is it correct ? 

### ISSUE THREAD

**Issue by ThanatSAISA** [unicfdlab/libAcoustics#55]

**Comment by ThanatSAISA** [comment]
Someone told me that the microphone must be located outside the computational domain.

**Comment by chen0mou0mou** [comment]
Hi, I think it should be far enough no matter if it is inside or outside. Usually, it is outside the computational domain.

**Comment by ThanatMU** [comment]
> 

How far it has to be from the source ?

**Comment by chen0mou0mou** [comment]
> 

It depends on your problem. I simulate the flow past cylinder. The far-field distance from the source is about 100 diameter.

**Comment by ThanatSAISA** [comment]
Actually I am currently simulate flow past cylinder too, then compare with
experiment. But, the experiment was done with  microphone located 1.4 m
away from source (diameter 42 mm). Its distance is obviously smaller than
100D
That s why, I want to know the criteria for the far field distance
selection.

In the bigger case  with more complicate geometry. The experiment was done
with the microphone located very near to the source. I am so worry about
this issue.

**Comment by chen0mou0mou** [comment]
Hi, I think there is no criteria. For the cylinder case, 50D, 100D and 200D are all possible. I think the value of our simulation should be consistent with the experiment that we want to use for validation.
