### ISSUE TITLE
v1912 Installation

### ISSUE THREAD

**Issue by heydarimorteza** [unicfdlab/libAcoustics#56]
Hello,
I get the following error along with some other errors when I run ./makeLib.sh located at Sources/lib:

_analogies/Curle/Curle.C:174:1: warning: null character(s) ignored_

However, installation completes and I can run the tutorials. When I run my own case, I get an error about the CurleAnalogy, why I have chosen fWH method. Does this negatively affect the results? Is there any way to fix the installation issue?
I should add that I use Openfoam v1912. 

Thank you.

**Comment by unicfdlab** [comment]
Try to use the libAcoustics for v2012 or v2112, we fixed sum bugs and added tests.
