### ISSUE TITLE
Could libAcoustics get the field of sound pressure distribution?

### ISSUE THREAD

**Issue by lianjieyu** [unicfdlab/libAcoustics#57]
Dear author,
I wonder if the libAcoustics can write fields of sound pressure just like the Cule function in OpenFOAM. Because I wnat to view the distribution of FWH results.

**Comment by chen0mou0mou** [comment]
Add as many probes as you want, so that you will get the sound pressure distribution.

**Comment by lianjieyu** [comment]
I see. Thank you very much.

**Comment by JustthanuMU** [comment]
> Do you success in doing this. I try to do this too. Can you share the case to me? 
 Thank you

**Comment by lianjieyu** [comment]
Sorry, I have not completed it.

**Comment by chen0mou0mou** [comment]
> Sorry, I have not completed it.

Hi，

This issue has my case set.
https://github.com/unicfdlab/libAcoustics/issues/53

Regards,
Guanjiang
