### ISSUE TITLE
What equation the option "Ffowcs～" solve?

### ISSUE THREAD

**Issue by Kousuke30425** [unicfdlab/libAcoustics#58]
Reading the tutorial PDF, I found the equation which is solved for the option "Curle", but I couldn't find the integral form for the "Ffowcs～".
Of course I know the differential form,  but I want to know what equation is exactly calculated by libAcoustics.

Thank you for any information.

**Comment by eacfd** [comment]
You can find all equations in this paper [https://doi.org/10.2514/6.2010-3711](url)

Regards.

**Comment by Kousuke30425** [comment]
Thank you for the information!
