### ISSUE TITLE
How to determine the dRef in fwhCommonSettings?

### ISSUE THREAD

**Issue by chancesFOAM** [unicfdlab/libAcoustics#59]
As it is suggested in the title, how to determine the parameter dRef in fwhCommonSettings?
I checked the code file of fwh and found how dRef is used. The sound pressure will be devided by dRef at the end of the computation. Hence, it will finally determine the amplitude of the SPL curve, and has no influence to the frequency. 
If I want to perform a 2-D cylinder computation with diameter D ,pesudo span length L (for openfoam it is a fake 3-D) and freestream velocity U or other fluid parameters, how do I determine this parameter dRef?

**Comment by unicfdlab** [comment]
The dRef value was added in the first version of the library for SPL estimation from 2D simulation, but this is not correct approach. This setting is ignored if dref value less then 0. You need to use the Kato correction (https://doi.org/10.1016/j.compfluid.2005.07.006) to evaluate the acoustic pressure in a pseudo 3D calculation. We removed dRef value from the latest version of the library and we want to add Kato correction in the future.
