### ISSUE TITLE
Fwh Control Surface after postProcessing & Setting Ufwh for impermeable blade surface

### ISSUE THREAD

**Issue by xevious54** [unicfdlab/libAcoustics#61]
Hey, I want to know if it is possible to write the integrated Fwh control surface as vtk or any format during the runtime for visualization of data after the fft has been ran?

Also, I want to do a study of noise sources and want to investigate the noise of impermeable blade surface vs permeable surface (which is easier to do). 

For the blade surface, say a two-bladed rotor with rpm of 4800, how do we set the U0, and Ufwh? since the Ufwh would vary along the span of the blade, we cannot simply set it as the tip speed, right?

**Comment by unicfdlab** [comment]
We updated tutorials in the latest version of the library. I think that the rotatingSphere (https://github.com/unicfdlab/libAcoustics/tree/digitef-dev-2012/Tutorials/rotatingSphere) case will help you. Try to set nonUniformSurfaceMotion true; Ufwh (.0 .0 .0); U0 (.0 .0 .0) for rotating blades
