### ISSUE TITLE
libAcoustics v2012 installation issues

### ISSUE THREAD

**Issue by jomarchris** [unicfdlab/libAcoustics#63]
I'm having an issue installing libAcoustics onto dev v2012 using the wmake command. The following errors appear (as shown in bold) below.

wmake libso .
wmakeLnIncludeAll: running wmakeLnInclude on dependent libraries:
    **wmakeLnInclude error: base directory /opt/openfoam-dev/src/transportModels/compressible/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam-dev/src/TurbulenceModels/turbulenceModels/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam-dev/src/TurbulenceModels/incompressible/ does not exist
    wmakeLnInclude error: base directory /opt/openfoam-dev/src/TurbulenceModels/compressible/ does not exist**
Make/linux64GccDPInt32Opt/files:5: *** missing separator.  Stop.
Make/linux64GccDPInt32Opt/files:5: *** missing separator.  Stop.
wmakeLnIncludeAll: running wmakeLnInclude on dependent libraries:
    wmakeLnInclude: linking include files to ../../lib//lnInclude
Making dependency list for source file surfaceNoise.C
Making dependency list for source file Interpolator.C
Making dependency list for source file FileInterface.C
g++ -std=c++14 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam-dev/src/randomProcesses/lnInclude -I/opt/openfoam-dev/src/sampling/lnInclude -I../../lib/lnInclude -I/include -IlnInclude -I. -I/opt/openfoam-dev/src/OpenFOAM/lnInclude -I/opt/openfoam-dev/src/OSspecific/POSIX/lnInclude   -fPIC -c FileInterface/FileInterface.C -o Make/linux64GccDPInt32Opt/FileInterface/FileInterface.o
g++ -std=c++14 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam-dev/src/randomProcesses/lnInclude -I/opt/openfoam-dev/src/sampling/lnInclude -I../../lib/lnInclude -I/include -IlnInclude -I. -I/opt/openfoam-dev/src/OpenFOAM/lnInclude -I/opt/openfoam-dev/src/OSspecific/POSIX/lnInclude   -fPIC -c Interpolator/Interpolator.C -o Make/linux64GccDPInt32Opt/Interpolator/Interpolator.o
g++ -std=c++14 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam-dev/src/randomProcesses/lnInclude -I/opt/openfoam-dev/src/sampling/lnInclude -I../../lib/lnInclude -I/include -IlnInclude -I. -I/opt/openfoam-dev/src/OpenFOAM/lnInclude -I/opt/openfoam-dev/src/OSspecific/POSIX/lnInclude   -fPIC -c surfaceNoise.C -o Make/linux64GccDPInt32Opt/surfaceNoise.o
In file included from surfaceNoise.C:100:
**createFields.H: In function ‘int main(int, char**)’:
createFields.H:26:35: error: ‘class Foam::IOdictionary’ has no member named ‘get’; did you mean ‘set’?
   26 |     fileName inputFileName = dict.get<word>("inputFileName");
      |                                   ^~~
      |                                   set
createFields.H:26:43: error: expected primary-expression before ‘>’ token
   26 |     fileName inputFileName = dict.get<word>("inputFileName");
      |                                           ^
make: *** [/opt/openfoam-dev/wmake/rules/General/transform:26: Make/linux64GccDPInt32Opt/surfaceNoise.o] Error 1**

**Comment by eacfd** [comment]
Please check your environment variables and OpenFOAM folder, the base files are missing in the openfoam-dev directory.
