### ISSUE TITLE
Problem when the libAcoustic is used for twoPhaseEulerFoam

### ISSUE THREAD

**Issue by lianjieyu** [unicfdlab/libAcoustics#64]
Hi, thank you for your contribution to the acoustic solver. But I found some problem when I used the libAcoustic for twoPhaseEulerFoam. The example is obtained from tutorials in OpenFOAM, and is attached in the followding. I hope you could find the answer why the lib cannot be applied in this case.

Best wishes.

[mixerVessel2D.zip](https://github.com/unicfdlab/libAcoustics/files/7761345/mixerVessel2D.zip)

**Comment by unicfdlab** [comment]
Hi, first of all, I would like to warn you, that libAcoustics uses acoustics analogies and therefore, it is not applicable for cases where control surfaces are located in region with alternating in time and space properties (mainly, density and speed of sound). It is assumed that noise propagates in uniform homogeneous medium.

Second, it is better to attach raw text files with console output from solver (log) for diagnosis together a direct question containing clear description of confusing program behavior.

**Comment by lianjieyu** [comment]
Thank you very much for your tips. I just want to try such solver to explore two-phase flows noise, without accuracy. 

The attachment is my new case with output file. You can run it with 'Allrun' anytime.

Hope for your reply.

[mixerVessel2D.zip](https://github.com/unicfdlab/libAcoustics/files/7838814/mixerVessel2D.zip)

**Comment by unicfdlab** [comment]
Can you please upload here a piece of simulation log and your question itself.
