### ISSUE TITLE
airfoil trailing edge noise

### ISSUE THREAD

**Issue by ereeenc** [unicfdlab/libAcoustics#65]
Hi to all!

I am a 4th year aeronautical engineering student who interested in OpenFOAM and aeroacoustic for about 3 months. It is hard to use OpenFOAM because it is too complicated for me. I am working on airfoil trailing edge noise. When i searching, i found this topic on github. I need help for my project. Could you show me a way how can i progress in my project.

Thanks in advance.

**Comment by unicfdlab** [comment]
Hi, you can use next materials:
- OpenFOAM training track (a bit outdated, but we plan to update it) https://github.com/unicfdlab/TrainingTracks/tree/master/OpenFOAM
- cfd-online.com threads: https://www.cfd-online.com/Forums/tags/libacoustics.html
- references from dedicated RG project: https://www.researchgate.net/project/libAcoustics-Acoustics-analysis-library-for-OpenFOAM

**Comment by oguzkaann** [comment]
Hi to everyone,
I studied the materials from this link. (https://github.com/unicfdlab/TrainingTracks/tree/master/OpenFOAM) But I couldn't understand how to proceed. I am using OFv2012. ı tried running one tutorial and ı downlanded and ınstalled libAcoustic but ı couldn't run. Please help me for a one application.

**Comment by unicfdlab** [comment]
> Hi to everyone, I studied the materials from this link. (https://github.com/unicfdlab/TrainingTracks/tree/master/OpenFOAM) But I couldn't understand how to proceed. I am using OFv2012. ı tried running one tutorial and ı downlanded and ınstalled libAcoustic but ı couldn't run. Please help me for a one application.

Hi, GitHub issues work in a slightly different way.  You must try to solve the problem by yourself and when you fail you can upload direct questions (one problem - one question) with comprehensive information about environment which caused this failure (console output, settings, etc). It is better to use one new thread per each problem. Please, check also that problem is not in "closed" list
