### ISSUE TITLE
install libacoustic in openfoam7

### ISSUE THREAD

**Issue by zhangmuElias** [unicfdlab/libAcoustics#66]
Dear everyone：

I am trying installing libacoustic in openfoam7 in Ubuntu, but after running ./wmakeAll.sh
it shows that
 `dell-123@Precision-7920-Tower:~/Downloads/libAcoustics-master/OpenFOAM-4.1$ ./wmakeAll.sh 
wmake libso .
make: *** No rule to make target '/opt/openfoam7/src/OpenFOAM/lnInclude/Xfer.H', needed by 'Make/linux64GccDPInt32Opt/SoundObserver/SoundObserver.C.dep'.  Stop.
make: *** No rule to make target '/opt/openfoam7/src/OpenFOAM/lnInclude/Xfer.H', needed by 'Make/linux64GccDPInt32Opt/FileInterface/FileInterface.C.dep'.  Stop.`
After checking the directory /opt/openfoam7/src/OpenFOAM/lnInclude/, there is no file named Xfer.H, does anyone know how to solve this problem? Because I need to couple openfoam7 with calculix to run fis case, so it's best for me to use of7.

Best regards
Mu
04.01.2022

**Comment by unicfdlab** [comment]
Hi, sorry for the long reply. We do not support openfoam.org version (since support of multiple versions is very time consuming). I recommend you to use OpenFOAM+. Current supported version is 2012, next version is in progress.

**Comment by zhangmuElias** [comment]
OK, I have installed it on of 4.1, thank you very much~
