### ISSUE TITLE
Could libAcoustics OpenFOAM+ v1912  version be used for OpenFOAM+ v1906?

### ISSUE THREAD

**Issue by chandukec** [unicfdlab/libAcoustics#67]
Hello, 
Many thanks for this wonderful library. I have OpenFOAM v1906 in my workstation, could ibAcoustics OpenFOAM+ v1912 be used for this version. Is there any document detailing the method to install libAcoustics in OpenFOAM? Also, is there any tutorial showing the use of FWH utility ? Any comment/suggestion will be a great help, thanks in advance.

**Comment by unicfdlab** [comment]
Hello, despite presence of previous versions, I strongly recommend to use latest one. Because only latest version of libAcoustics includes all bug fixes and introduced features

**Comment by chandukec** [comment]
@unicfdlab Thanks a lot for your prompt reply and help. Is there any documentation regarding the installation guide?

**Comment by unicfdlab** [comment]
We have only Training Track materials: https://github.com/unicfdlab/TrainingTracks/tree/master/OpenFOAM

**Comment by chandukec** [comment]
@unicfdlab Thanks for your post. Sorry, I guess I misunderstood your post, but I am only interested in noise calculation using FWH model using libAcoustic. My question was how to couple OpenFOAM v1906 with `libAcoustic`. I am extremely sorry for being naive in this issue. I downloaded the `libAcoustic` but I am unable to couple this with the OpenFOAM v1906. Or just wanted to install this utility called `libAcoustic` for using the FWH model (already installed OpenFOAM v1906 in my workstation). Many thanks in advance.

**Comment by chandukec** [comment]
@unicfdlab I successfully managed to installed it in the OpenFoam v1906. I went inside the` libAcoustics-digitef-dev-1912/Sources`
 and just typed `./wlcleanAll.sh `and` ./wmakeAll.sh,` that's all! Sorry for bothering you. Now checking for the tutorials, thanks :)
