### ISSUE TITLE
Huge difference between my curle and fwh results

### ISSUE THREAD

**Issue by zhangmuElias** [unicfdlab/libAcoustics#69]
Dear everyone
I met a problem when I simulated the acoustic noise of naca0018 airfoil (2D case) with LES and curle and fwh. The control surface of the 2 methods are both the boundary of naca0018(wall).
Some important information is in this picture:
![case information](https://user-images.githubusercontent.com/97109440/150214547-db8b8e87-11ec-45a2-8adc-fd4845223173.jpg)

and I don't know why there are huge differences between the acoustic pressure fluctuation of the same Receiver point of curle (the larger one) and fwh analogy (the smaller one):
 
![curle](https://user-images.githubusercontent.com/97109440/150213890-19ddba35-e833-47e9-88aa-4e1b21e8bfef.png)
![FWH](https://user-images.githubusercontent.com/97109440/150213893-3f9032a2-fba4-44fc-978d-773097914c02.png)
 
Does somebody know why? I also attached my setting below:
[setting.zip](https://github.com/unicfdlab/libAcoustics/files/7900590/setting.zip)

**Comment by unicfdlab** [comment]
Hi, can you try this case with OpenFOAM+2012? I guess, that might be just an error because we fix bugs only in new releases

**Comment by zhangmuElias** [comment]
hello, thanks for your reply, do you mean only curle results are wrong in this version or both curle and fwh results are wrong? 
May you tell me where the bug is? Maybe I can also try to fix it since for a short time I need to use this version of OF to simulate fsi problems. Thanks again.

best regards 
Runze

**Comment by unicfdlab** [comment]
They might be both correct but use different set of coefficients, since 2D simulations with libAcoustics require multiplying coefficient which is arbitrary to some extents

**Comment by unicfdlab** [comment]
We have verified library only later for OpenFOAM-1812 and only for 3D cases. Actually, Curle and FWH analogies were orignally derived for 3D case

**Comment by zhangmuElias** [comment]
Is it possible I processing the result data to make them right by multiplying their right coefficients.

**Comment by unicfdlab** [comment]
I'm not sure what you want to do. But anyway you have to check that   ** dRef **      , ** rho ** and other common properties are set equal in FWH and Curle cases

**Comment by zhangmuElias** [comment]
Sure, I will double check my parameters. Thanks!
