### ISSUE TITLE
Cannot compile the libAcoustics on Openfoam 4.0 & 4.1

### ISSUE THREAD

**Issue by teletubbiess** [unicfdlab/libAcoustics#7]
Dear all,

I tried to compile the library on both 4.0 and 4.1 version, while they both failed. Could you please help me out?

The error I met is:
/usr/bin/ld: cannot find -lAcoustics
collect2: ld returned 1 exit status
make: *** [/home/minghangli/OpenFOAM/minghangli-4.1/platforms/linux64GccDPInt64Opt/bin/surfaceNoise] Error 1

I did not find Acoustics.so anywhere. What should I do now? 

Thank you.

Kind regards,
Henry LOO

**Comment by vkorchagova** [comment]
Hello Henry,

This error appears when you try to compile surfaceNoise application before libAcoustics compilation. Be sure that libAcoustics was compiled successfully.
You should run script ./makeLib.sh to compile libAcoustic and app. If you will meet some errors just send the log. 

Best regards,
Victoria

**Comment by teletubbiess** [comment]
Dear Victoria,

Thank you for your reply. I did run the script ./makeLib.sh to compile
both.

Then I ran the command separately, ./makeLib.sh whose log file is attached
in log.makeLib.sh. The errors cannot be written in this log file. So they
are pasted here for your convenience.

This is not dpkg install-info anymore, but GNU install-info
See the man page for ginstall-info for command line arguments
ln: failed to create symbolic link `./libfftw3.so': File exists
ln: failed to create symbolic link `./libfftw3.so.3': File exists
ln: failed to create symbolic link `./libfftw3.so.3.3.2': File exists
wmakeLnInclude: linking include files to ./lnInclude
ln: failed to create symbolic link `./f77funcs.h': File exists
Making dependency list for source file
samplingBEM/soundPressureSampler/soundPressureSampler.C
Making dependency list for source file
samplingBEM/sampledSurface/writers/gmsh/gmshSurfaceWriter.C
Making dependency list for source file
analogies/FfowcsWilliamsHawkings/FfowcsWilliamsHawkings.C
Making dependency list for source file
analogies/FfowcsWilliamsHawkings/Farassat1AFormulation.C
Making dependency list for source file
analogies/FfowcsWilliamsHawkings/fwhFormulation.C
Making dependency list for source file analogies/Curle/Curle.C
Making dependency list for source file
analogies/AcousticAnalogy/AcousticAnalogy.C
Making dependency list for source file FoamFourierAnalysis/FoamFftwDriver.C
Making dependency list for source file SoundObserver/SoundObserver.C
FoamFourierAnalysis/FoamFftwDriver.C: In member function
‘Foam::autoPtr<Foam::List<Foam::complex> >
Foam::FoamFftwDriver::simpleComplexForwardTransform() const’:
FoamFourierAnalysis/FoamFftwDriver.C:24:75: warning: use of old-style cast
[-Wold-style-cast]
FoamFourierAnalysis/FoamFftwDriver.C:25:75: warning: use of old-style cast
[-Wold-style-cast]
FoamFourierAnalysis/FoamFftwDriver.C: In member function
‘Foam::autoPtr<Foam::Pair<Foam::List<double> > >
Foam::FoamFftwDriver::simpleScalarForwardTransform() const’:
FoamFourierAnalysis/FoamFftwDriver.C:88:75: warning: use of old-style cast
[-Wold-style-cast]
FoamFourierAnalysis/FoamFftwDriver.C:89:75: warning: use of old-style cast
[-Wold-style-cast]
In file included from analogies/FfowcsWilliamsHawkings/fwhFormulation.C:1:0:
analogies/FfowcsWilliamsHawkings/FfowcsWilliamsHawkings.H:80:18: warning:
‘Foam::functionObjects::fwhFormulation’ is already a friend of
‘Foam::functionObjects::FfowcsWilliamsHawkings’ [enabled by default]
analogies/FfowcsWilliamsHawkings/FfowcsWilliamsHawkings.H:81:18: warning:
‘Foam::functionObjects::Farassat1AFormulation’ is already a friend of
‘Foam::functionObjects::FfowcsWilliamsHawkings’ [enabled by default]
analogies/FfowcsWilliamsHawkings/FfowcsWilliamsHawkings.H:82:18: warning:
‘Foam::functionObjects::fvmInterpolationFormulation’ is already a friend of
‘Foam::functionObjects::FfowcsWilliamsHawkings’ [enabled by default]
In file included from analogies/FfowcsWilliamsHawkings/fwhFormulation.C:2:0:
analogies/FfowcsWilliamsHawkings/fwhFormulation.H:29:5: error: expected
unqualified-id before ‘using’
analogies/FfowcsWilliamsHawkings/fwhFormulation.H:55:10: error:
‘tdPrimitive’ was not declared in this scope
analogies/FfowcsWilliamsHawkings/fwhFormulation.H:55:28: error: template
argument 1 is invalid
analogies/FfowcsWilliamsHawkings/fwhFormulation.H:55:30: error: expected
unqualified-id before ‘>’ token
analogies/FfowcsWilliamsHawkings/fwhFormulation.C: In constructor
‘Foam::functionObjects::fwhFormulation::fwhFormulation(const
Foam::functionObjects::FfowcsWilliamsHawkings&)’:
analogies/FfowcsWilliamsHawkings/fwhFormulation.C:13:5: error: class
‘Foam::functionObjects::fwhFormulation’ does not have any field named ‘ni_’
analogies/FfowcsWilliamsHawkings/fwhFormulation.C: In member function ‘void
Foam::functionObjects::fwhFormulation::initialize()’:
analogies/FfowcsWilliamsHawkings/fwhFormulation.C:110:5: error: ‘ni_’ was
not declared in this scope
analogies/FfowcsWilliamsHawkings/fwhFormulation.C: In member function
‘virtual void Foam::functionObjects::fwhFormulation::update()’:
analogies/FfowcsWilliamsHawkings/fwhFormulation.C:262:9: error: ‘ni_’ was
not declared in this scope
make: ***
[/home/minghangli/OpenFOAM/OpenFOAM-4.1/platforms/linux64GccDPInt64Opt/libAcoustics-master/OpenFOAM-4.1/lib/analogies/FfowcsWilliamsHawkings/fwhFormulation.o]
Error 1

Thank you for your time indeed. I do appreciate your help.

Kind regards,
Henry



2018-04-16 20:04 GMT+10:00 vkorchagova <notifications@github.com>:

**Comment by unicfdlab** [comment]
Hi Henry,

which version of gcc/g++ are you using?
Please, run 'g++ -v' and paste result here

--
Matvey

**Comment by teletubbiess** [comment]
Hi Matvey,

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro
4.6.4-1ubuntu1~12.04'
--with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs
--enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr
--program-suffix=-4.6 --enable-shared --enable-linker-build-id
--with-system-zlib --libexecdir=/usr/lib --without-included-gettext
--enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6
--libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu
--enable-libstdcxx-debug --enable-libstdcxx-time=yes
--enable-gnu-unique-object --enable-plugin --enable-objc-gc
--disable-werror --with-arch-32=i686 --with-tune=generic
--enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu
--target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.4 (Ubuntu/Linaro 4.6.4-1ubuntu1~12.04)

Is it too old?

Thank you.

2018-04-16 20:54 GMT+10:00 UniCFD <notifications@github.com>:

**Comment by unicfdlab** [comment]
Actually, yes.
You should switch to something newer, 6.3 or later.
For example, I'm using 7.1

--
Matvey

**Comment by teletubbiess** [comment]
Thank you. I will switch to higher version and then let you know if it is
working or not.

Thanks again.


2018-04-16 20:58 GMT+10:00 UniCFD <notifications@github.com>:
