### ISSUE TITLE
Is there any difference between "master" and digitef-dev-2012 ?

### ISSUE THREAD

**Issue by mingLoveHuTao** [unicfdlab/libAcoustics#70]
Hello~
I'm a postgraduate and using this lib to estimate cavitation flow noise.
My senior used this lib, the master branch, around 4 years ago and now I'm following his work.
Now I can run a 2D cavitation hydrofoil case with FW-H in the master branch using OpenFOAM 5.x. I'm still a newer of libAcoustics and OpenFOAM. I have read the forum and I found in the digitef-dev-2012 branch the developer fixed some bugs.
I wonder if there is any difference of the core code between "master" and "digitef-dev-2012". Is one better than the other? And could you give me some suggestions about which branch to use?

Another question: what's the meaning of fftFreq in the "commonSettings" file? Is it a parameter in the process of FFT? For example, I found the pressure disturbances at every moment in "XXXX-time.dat" file of both observers A and B are the same. But the fft results differ.
observers
        {
                A
                {
                	position	(0.4 0.8 0.0);
                	pRef		1.0e-6;
                	fftFreq		100;
                }
                B
                {
                	position	(0.4 0.8 0.0);
                	pRef		1.0e-6;
                	fftFreq		1024;
                }
        }

**Comment by unicfdlab** [comment]
Hi, master branch contains only old version of the library. While digitef-dev-2021 contains version for OpenFOAM+ 2012. We resolve bugs only in new versions. Therefore, the earlier version you use, the more bugs it has (probably).

**Comment by mingLoveHuTao** [comment]
Thanks for your reply. 
So if I don't meet bugs when using, I could assume the acoustic data is right without any calculation errors, right?

**Comment by unicfdlab** [comment]
No, I didn't say that. I said only that we fix bugs in new version.

**Comment by mingLoveHuTao** [comment]
I see, thank you very much 😄
