### ISSUE TITLE
Elementary FWH surface source.

### ISSUE THREAD

**Issue by Charly-28** [unicfdlab/libAcoustics#71]
Hello, I would like to access the elementary FWH surface source.
How to extract the acoustic contribution of an element from the surface source?
Thanks

**Comment by unicfdlab** [comment]
Hi, it is not possible to extract contribution of a single element using libAcoustics standard interfaces.
However, you can write your own code, which takes data from internal libAcoustics data structures qds_ and fds_, which store contribution from monopole and dipole face sources, respectively. See, for example https://github.com/unicfdlab/libAcoustics/blob/digitef-dev-2012/Sources/lib/analogies/FfowcsWilliamsHawkings/Farassat1AFormulation.C lines 232 and 283.

Also, you can create custom STL containing only 1 triangle of interest

**Comment by Charly-28** [comment]
Hi, thanks for you reply.
I will write my own code based on your example.
Thanks,
Charly

**Comment by unicfdlab** [comment]
Just a few hours ago I've this tutorial on libAcoustics API by Chalmers TU: http://www.tfd.chalmers.se/~hani/kurser/OS_CFD_2021/DebarsheeGhosh/OSCFD21_FinalPresentation.pdf

**Comment by Charly-28** [comment]
Very nice.
Thanks again.
Charly
