### ISSUE TITLE
On the choice of the surface for FWH Analogy

### ISSUE THREAD

**Issue by windseacn** [unicfdlab/libAcoustics#78]
Hello, I'm interested in CAA and find this library is very useful for beginners. I tested the vortexshed tutorial with different surfaces, the cylinder surface (default in the tutorial), a square box with the side length equal to the diameter of the cylinder and one larger cylindrical surface with its radius equal to the  cylinder diameter, these three surfaces are shown below:
![surface](https://user-images.githubusercontent.com/87025938/169061809-7044f2dd-4636-4a4c-b06c-8864c8e6107d.png)

The sound pressure levels for these three cases are shown below.

![untitled](https://user-images.githubusercontent.com/87025938/169061903-c4eab9f9-d98b-446f-ad1a-9c244ff13cd6.jpg)

From my limited knowledge on this subject, the results from these three surface configurations should be very close as the Mach number is very low. However, the result with the square surface is quite different from the others, there exists a second peak in the spectrum. While the result from larger cylindrical surface is close that from rigid body surface. Does this mean the results are sensitive to the shape of the surface chosen?

**Comment by unicfdlab** [comment]
Hello, 

I think that, the problem with square is related to the fact that the square surface intersects the cylinder patch which caused the problems with data interpolation. Try to use square with side length equal to 4R.
The difference between patch surface and 2R circle caused by the influence of the vortex wake.

Regards.

**Comment by windseacn** [comment]
Thanks for your reply. The difference between patch surface and 2R circle is minor, and could be expected.

I have tried square with side length equal to 3R, which is not good either as below.
![untitled1](https://user-images.githubusercontent.com/87025938/169306406-438a4767-195d-440a-bb71-12028b740aa2.jpg)

I will try whether the result for  square with side length equal to 4R and report later.

**Comment by windseacn** [comment]
For four different surfaces as below
![surface2](https://user-images.githubusercontent.com/87025938/169343734-d4e7fcca-c56b-48b0-94e2-af51f69707f0.png)

The SPLs for these four configurations are
![untitled2](https://user-images.githubusercontent.com/87025938/169343903-118bb2a5-0e42-460d-ae69-07a8a873397b.jpg)

It's interesting to note that the frequency of the maximum SPL changes if a larger square surface is used.

**Comment by unicfdlab** [comment]
Could you share your case with square surfaces?

**Comment by windseacn** [comment]
The case is the same as the vortexShed tutorial from the library, with more surfaces added.

[vortexShedm2d.tar.gz](https://github.com/unicfdlab/libAcoustics/files/8738253/vortexShedm2d.tar.gz)

**Comment by windseacn** [comment]
I have tested more surfaces,  some low resolution cylinder surfaces with different segments and radius 2R
![surface4](https://user-images.githubusercontent.com/87025938/169673780-2a2bf43c-34e1-4109-aea0-61833591baa5.png)

The SPL results are shown below
![untitled4](https://user-images.githubusercontent.com/87025938/169673789-3742ae9c-3121-4cfe-9464-041981dfee75.jpg)
It can be seen that for these surfaces, there exist additional SPL peaks around double and quadruple base frequencies.  As the number of segments increases, i.e., the cylinder becomes smoother, the contributions from higher frequencies become lower. I wonder whether this is physical result, or induced by some numerical issues?

**Comment by windseacn** [comment]
Cai et al, have tested different square boxes for flow around cylinder with FWH analogy, from which this phenomenon is not observed.
![surface3](https://user-images.githubusercontent.com/87025938/169674099-6ca5a55f-aee8-4d05-a8f0-e7dc2f54ca66.png)

------------
A numerical study of transient flow around a cylinder and aerodynamic sound radiation
https://link.springer.com/article/10.1134/S0869864318030022

**Comment by unicfdlab** [comment]
The FW-H stl surfaces have poor resolution (2 cells per square side), try to create and use square surface with more cells per side.

Regards
