### ISSUE TITLE
FWH: Incorrect Sound Pressure Magnitude

### ISSUE THREAD

**Issue by strootg** [unicfdlab/libAcoustics#8]
Hello,
I have set up the validation cases:
-Sound generation by a two-dimensional circular cylinder in a uniform flow, Osamu Inoue and Nozomu Hatakeyama
-Mechanism of aeroacoustic sound generation and reduction in a flow past oscillating and fixed cylinders, Yuji Hattori

The correct lift and drag are retrieved from the flow solver and these values can be used to find sound directivity by a correctly with some accuracy, but the FWH acoustic solver provides values with a much too high of a magnitude.

See here: https://imgur.com/a/nwM333W
Case files can be provided as needed. I believe this issue may have something to do with Copy length discussing by Tang in "Numerical Simulation of Flow-Induced Noise by Means of the Hybrid Method with LES and Aeroacoustic Analogy"

Best

Greg

**Comment by engenegr** [comment]
Hi!

I've responded to your e-mail from cfd-online. However, you have an option "do not receive any emails" on the forum, so I've sent it directly to your gmail box. 

Ilya.

**Comment by vkorchagova** [comment]
Hi Greg,
Could you send us the case? We'll check your settings.

**Comment by strootg** [comment]
Hello,

I ran two different cases. One with flower over a fixed cylinder and one with an oscillating cylinder and a fixed cylinder. Both cases gave me the correct plots, but the incorrect magnitudes. I have attached information for the first validation case. If you have time and are interested, I can send files for the second validation case as well. It is of interest since it utilizes pimpleDyMFoam and libAcoustics


[Cylinder_Cross_Flow.tar.gz](https://github.com/unicfdlab/libAcoustics/files/2022744/Cylinder_Cross_Flow.tar.gz)
![single_cyl_data](https://user-images.githubusercontent.com/39132114/40310674-2bced642-5cd3-11e8-9ef5-811573543636.png)
[sound_generation_by_a_twodimensional_circular_cylinder_in_a_uniform_flow.pdf](https://github.com/unicfdlab/libAcoustics/files/2022746/sound_generation_by_a_twodimensional_circular_cylinder_in_a_uniform_flow.pdf)

**Comment by wanglican** [comment]
Hi strootg,
     When I run the case (Cylinder_Cross_Flow.tar.gz), it occurs following errors:

```
Reading analogy settings
--> FOAM FATAL IO ERROR: 
keyword writeFft is undefined in dictionary "/home/Desktop/Cylinder_Cross_Flow/system/controlDict.functions.monopole2DFwhTest"
file: /home/Desktop/Cylinder_Cross_Flow/system/controlDict.functions.monopole2DFwhTest from line 3 to line 23.
    From function const Foam::entry& Foam::dictionary::lookupEntry(const Foam::word&, bool, bool) const
    in file db/dictionary/dictionary.C at line 441.
```
    I did not find any word "writeFft " in your file.

**Comment by unicfdlab** [comment]
The paper sound_generation_by_a_twodimensional_circular_cylinder_in_a_uniform_flow.pdf mentioned above uses 2D formulation of Green function for Acoustic analogy. However, our implementation is 3D, so it is not strictly applicable to the mentioned above case.
