### ISSUE TITLE
Curle and FWH

### ISSUE THREAD

**Issue by chen0mou0mou** [unicfdlab/libAcoustics#89]
Hi,

I have a small question. 
I simulate the flow past a cylinder and predict the noise using libacoustics. If I use FWH and choose the cylinder surface as the control (integral) surface, this FWH set has the same core as the curle method. The results from this FWH set and curle set are the same. I want to confirm this. 

Thank you,
Guanjiang

**Comment by mkraposhin** [comment]
Hi!

Yes and no simultaneously. Theoretically FWH reduces to Curle when a control surface encompases a body. However, in our formulation we don't account for retarded time  while integrating over a control surface in the Curle analogy implementation. While in FWH we do account for retarded time. Therefore, you should experience some difference between results.

**Comment by mkraposhin** [comment]
I think this question was addressed previously in other issues. Try searching in the "Closed" section.

**Comment by chen0mou0mou** [comment]
Thanks
