### ISSUE TITLE
LibAcoustics 4.1 Incompatible with PisoFoam?

### ISSUE THREAD

**Issue by HBRu** [unicfdlab/libAcoustics#9]
Dear all,

When I try to use libAcoustics in a OF4.1 PisoFoam case (that runs perfectly w/o the use of the library) I found the error message:

>> could not find rho

Tutorials for this library and this version all run with rhoPimpleFoam, but I am not into solving the energy equation.

Am I commiting any misuse of this library?

Yours faithfully,
Héctor

**Comment by unicfdlab** [comment]
Hi, Hector.

For the incompressible case you must specify the value for density at the infinity:
`
rho rhoInf;
rhoInf 1.2;
`

Also, please note that we found few small bugs in the source code. We will upload corrected version after running test cases.

Best wishes,
Matvey

**Comment by HBRu** [comment]
Hi Matvey,

This is what I'd done. If I don't put any of these two, the program let you know which is not specify. I mean, if rhoInf valus is missing it tells you.

The error I mentioned is weird, cause everything has been set correctly.

I posted a question on:

https://www.cfd-online.com/Forums/openfoam-programming-development/85450-acoustic-solver-openfoam-6.html#post703769

Thank you so much for your help and interest.

Best regards,
Héctor

**Comment by HBRu** [comment]
Issue closed. 
Thank you so much Matvey.
